/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyNameRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyNameDao extends DAOImpl<CtmsCompanyNameRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName, BigInteger> {

    /**
     * Create a new CtmsCompanyNameDao without any configuration
     */
    public CtmsCompanyNameDao() {
        super(CtmsCompanyName.CTMS_COMPANY_NAME, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName.class);
    }

    /**
     * Create a new CtmsCompanyNameDao with an attached configuration
     */
    public CtmsCompanyNameDao(Configuration configuration) {
        super(CtmsCompanyName.CTMS_COMPANY_NAME, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName> fetchById(BigInteger... values) {
        return fetch(CtmsCompanyName.CTMS_COMPANY_NAME.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName fetchOneById(BigInteger value) {
        return fetchOne(CtmsCompanyName.CTMS_COMPANY_NAME.ID, value);
    }

    /**
     * Fetch records that have <code>COMPANY_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName> fetchByCompanyId(BigInteger... values) {
        return fetch(CtmsCompanyName.CTMS_COMPANY_NAME.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>ENGLISH_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName> fetchByEnglishName(String... values) {
        return fetch(CtmsCompanyName.CTMS_COMPANY_NAME.ENGLISH_NAME, values);
    }

    /**
     * Fetch records that have <code>CHINESE_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyName> fetchByChineseName(String... values) {
        return fetch(CtmsCompanyName.CTMS_COMPANY_NAME.CHINESE_NAME, values);
    }
}
