/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyCatRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyCatDao extends DAOImpl<CtmsCompanyCatRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat, BigInteger> {

    /**
     * Create a new CtmsCompanyCatDao without any configuration
     */
    public CtmsCompanyCatDao() {
        super(CtmsCompanyCat.CTMS_COMPANY_CAT, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat.class);
    }

    /**
     * Create a new CtmsCompanyCatDao with an attached configuration
     */
    public CtmsCompanyCatDao(Configuration configuration) {
        super(CtmsCompanyCat.CTMS_COMPANY_CAT, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat> fetchById(BigInteger... values) {
        return fetch(CtmsCompanyCat.CTMS_COMPANY_CAT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat fetchOneById(BigInteger value) {
        return fetchOne(CtmsCompanyCat.CTMS_COMPANY_CAT.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat> fetchByCode(String... values) {
        return fetch(CtmsCompanyCat.CTMS_COMPANY_CAT.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>CODE = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat fetchOneByCode(String value) {
        return fetchOne(CtmsCompanyCat.CTMS_COMPANY_CAT.CODE, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyCat> fetchByName(String... values) {
        return fetch(CtmsCompanyCat.CTMS_COMPANY_CAT.NAME, values);
    }
}
