/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyGrpRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyGrpDao extends DAOImpl<CtmsCompanyGrpRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp, BigInteger> {

    /**
     * Create a new CtmsCompanyGrpDao without any configuration
     */
    public CtmsCompanyGrpDao() {
        super(CtmsCompanyGrp.CTMS_COMPANY_GRP, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp.class);
    }

    /**
     * Create a new CtmsCompanyGrpDao with an attached configuration
     */
    public CtmsCompanyGrpDao(Configuration configuration) {
        super(CtmsCompanyGrp.CTMS_COMPANY_GRP, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp> fetchById(BigInteger... values) {
        return fetch(CtmsCompanyGrp.CTMS_COMPANY_GRP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp fetchOneById(BigInteger value) {
        return fetchOne(CtmsCompanyGrp.CTMS_COMPANY_GRP.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp> fetchByCode(String... values) {
        return fetch(CtmsCompanyGrp.CTMS_COMPANY_GRP.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>CODE = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp fetchOneByCode(String value) {
        return fetchOne(CtmsCompanyGrp.CTMS_COMPANY_GRP.CODE, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyGrp> fetchByName(String... values) {
        return fetch(CtmsCompanyGrp.CTMS_COMPANY_GRP.NAME, values);
    }
}
