/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserGroupRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUserGroupDao extends DAOImpl<CtmsUserGroupRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup, BigInteger> {

    /**
     * Create a new CtmsUserGroupDao without any configuration
     */
    public CtmsUserGroupDao() {
        super(CtmsUserGroup.CTMS_USER_GROUP, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup.class);
    }

    /**
     * Create a new CtmsUserGroupDao with an attached configuration
     */
    public CtmsUserGroupDao(Configuration configuration) {
        super(CtmsUserGroup.CTMS_USER_GROUP, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchById(BigInteger... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup fetchOneById(BigInteger value) {
        return fetchOne(CtmsUserGroup.CTMS_USER_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>USER_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByUserId(BigInteger... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.USER_ID, values);
    }

    /**
     * Fetch records that have <code>GRP_LV1 IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByGrpLv1(String... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.GRP_LV1, values);
    }

    /**
     * Fetch records that have <code>GRP_LV2 IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByGrpLv2(String... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.GRP_LV2, values);
    }

    /**
     * Fetch records that have <code>GRP_LV3 IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByGrpLv3(String... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.GRP_LV3, values);
    }

    /**
     * Fetch records that have <code>UPDATED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByUpdatedBy(String... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.UPDATED_BY, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsUserGroup> fetchByUpdatedAt(Timestamp... values) {
        return fetch(CtmsUserGroup.CTMS_USER_GROUP.UPDATED_AT, values);
    }
}
