/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormPtyRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormPtyDao extends DAOImpl<CtmsCtFormPtyRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty, BigInteger> {

    /**
     * Create a new CtmsCtFormPtyDao without any configuration
     */
    public CtmsCtFormPtyDao() {
        super(CtmsCtFormPty.CTMS_CT_FORM_PTY, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty.class);
    }

    /**
     * Create a new CtmsCtFormPtyDao with an attached configuration
     */
    public CtmsCtFormPtyDao(Configuration configuration) {
        super(CtmsCtFormPty.CTMS_CT_FORM_PTY, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchById(BigInteger... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty fetchOneById(BigInteger value) {
        return fetchOne(CtmsCtFormPty.CTMS_CT_FORM_PTY.ID, value);
    }

    /**
     * Fetch records that have <code>CT_FORM_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByCtFormId(BigInteger... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.CT_FORM_ID, values);
    }

    /**
     * Fetch records that have <code>COMPANY_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByCompanyId(BigInteger... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>COMPANY_CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByCompanyCode(String... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_CODE, values);
    }

    /**
     * Fetch records that have <code>COMPANY_GRP_CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByCompanyGrpCode(String... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_GRP_CODE, values);
    }

    /**
     * Fetch records that have <code>ENGLISH_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByEnglishName(String... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.ENGLISH_NAME, values);
    }

    /**
     * Fetch records that have <code>CHINESE_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormPty> fetchByChineseName(String... values) {
        return fetch(CtmsCtFormPty.CTMS_CT_FORM_PTY.CHINESE_NAME, values);
    }
}
