/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsReportGrpHierRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsReportGrpHierDao extends DAOImpl<CtmsReportGrpHierRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier, BigInteger> {

    /**
     * Create a new CtmsReportGrpHierDao without any configuration
     */
    public CtmsReportGrpHierDao() {
        super(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier.class);
    }

    /**
     * Create a new CtmsReportGrpHierDao with an attached configuration
     */
    public CtmsReportGrpHierDao(Configuration configuration) {
        super(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier> fetchById(BigInteger... values) {
        return fetch(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier fetchOneById(BigInteger value) {
        return fetchOne(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.ID, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier> fetchByName(String... values) {
        return fetch(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.NAME, values);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier> fetchByCode(String... values) {
        return fetch(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>CODE = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier fetchOneByCode(String value) {
        return fetchOne(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.CODE, value);
    }

    /**
     * Fetch records that have <code>PARENT_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier> fetchByParentId(BigInteger... values) {
        return fetch(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>DISPLAY_SEQ IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsReportGrpHier> fetchByDisplaySeq(Long... values) {
        return fetch(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.DISPLAY_SEQ, values);
    }
}
