/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormServiceRecord;

import java.math.BigInteger;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormServiceDao extends DAOImpl<CtmsCtFormServiceRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService, BigInteger> {

    /**
     * Create a new CtmsCtFormServiceDao without any configuration
     */
    public CtmsCtFormServiceDao() {
        super(CtmsCtFormService.CTMS_CT_FORM_SERVICE, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService.class);
    }

    /**
     * Create a new CtmsCtFormServiceDao with an attached configuration
     */
    public CtmsCtFormServiceDao(Configuration configuration) {
        super(CtmsCtFormService.CTMS_CT_FORM_SERVICE, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService> fetchById(BigInteger... values) {
        return fetch(CtmsCtFormService.CTMS_CT_FORM_SERVICE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService fetchOneById(BigInteger value) {
        return fetchOne(CtmsCtFormService.CTMS_CT_FORM_SERVICE.ID, value);
    }

    /**
     * Fetch records that have <code>CT_FORM_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService> fetchByCtFormId(BigInteger... values) {
        return fetch(CtmsCtFormService.CTMS_CT_FORM_SERVICE.CT_FORM_ID, values);
    }

    /**
     * Fetch records that have <code>TYPE_CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService> fetchByTypeCode(String... values) {
        return fetch(CtmsCtFormService.CTMS_CT_FORM_SERVICE.TYPE_CODE, values);
    }

    /**
     * Fetch records that have <code>TYPE_OTHERS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCtFormService> fetchByTypeOthers(String... values) {
        return fetch(CtmsCtFormService.CTMS_CT_FORM_SERVICE.TYPE_OTHERS, values);
    }
}
