/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyHolderRecord;

import java.math.BigInteger;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyHolderDao extends DAOImpl<CtmsCompanyHolderRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder, BigInteger> {

    /**
     * Create a new CtmsCompanyHolderDao without any configuration
     */
    public CtmsCompanyHolderDao() {
        super(CtmsCompanyHolder.CTMS_COMPANY_HOLDER, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder.class);
    }

    /**
     * Create a new CtmsCompanyHolderDao with an attached configuration
     */
    public CtmsCompanyHolderDao(Configuration configuration) {
        super(CtmsCompanyHolder.CTMS_COMPANY_HOLDER, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder> fetchById(BigInteger... values) {
        return fetch(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder fetchOneById(BigInteger value) {
        return fetchOne(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.ID, value);
    }

    /**
     * Fetch records that have <code>COMPANY_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder> fetchByCompanyId(BigInteger... values) {
        return fetch(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>COMPANY_GRP_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder> fetchByCompanyGrpId(BigInteger... values) {
        return fetch(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.COMPANY_GRP_ID, values);
    }

    /**
     * Fetch records that have <code>START_DATE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder> fetchByStartDate(Date... values) {
        return fetch(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.START_DATE, values);
    }

    /**
     * Fetch records that have <code>END_DATE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompanyHolder> fetchByEndDate(Date... values) {
        return fetch(CtmsCompanyHolder.CTMS_COMPANY_HOLDER.END_DATE, values);
    }
}
