/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.daos;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompany;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyDao extends DAOImpl<CtmsCompanyRecord, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany, BigInteger> {

    /**
     * Create a new CtmsCompanyDao without any configuration
     */
    public CtmsCompanyDao() {
        super(CtmsCompany.CTMS_COMPANY, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany.class);
    }

    /**
     * Create a new CtmsCompanyDao with an attached configuration
     */
    public CtmsCompanyDao(Configuration configuration) {
        super(CtmsCompany.CTMS_COMPANY, com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchById(BigInteger... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany fetchOneById(BigInteger value) {
        return fetchOne(CtmsCompany.CTMS_COMPANY.ID, value);
    }

    /**
     * Fetch records that have <code>CODE IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCode(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CODE, values);
    }

    /**
     * Fetch a unique record that has <code>CODE = value</code>
     */
    public com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany fetchOneByCode(String value) {
        return fetchOne(CtmsCompany.CTMS_COMPANY.CODE, value);
    }

    /**
     * Fetch records that have <code>ENGLISH_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByEnglishName(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.ENGLISH_NAME, values);
    }

    /**
     * Fetch records that have <code>CHINESE_NAME IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByChineseName(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CHINESE_NAME, values);
    }

    /**
     * Fetch records that have <code>COMPANY_CAT_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCompanyCatId(BigInteger... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.COMPANY_CAT_ID, values);
    }

    /**
     * Fetch records that have <code>BR_NUMBER IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByBrNumber(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.BR_NUMBER, values);
    }

    /**
     * Fetch records that have <code>ADDRESS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByAddress(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>PHONE_NUMBER IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByPhoneNumber(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.PHONE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>STATUS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByStatus(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.STATUS, values);
    }

    /**
     * Fetch records that have <code>COMPANY_GRP_ID IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCompanyGrpId(BigInteger... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.COMPANY_GRP_ID, values);
    }

    /**
     * Fetch records that have <code>REQUESTED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByRequestedBy(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.REQUESTED_BY, values);
    }

    /**
     * Fetch records that have <code>REQUESTED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByRequestedAt(Timestamp... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.REQUESTED_AT, values);
    }

    /**
     * Fetch records that have <code>REMARKS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByRemarks(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.REMARKS, values);
    }

    /**
     * Fetch records that have <code>CTO_REMARKS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCtoRemarks(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CTO_REMARKS, values);
    }

    /**
     * Fetch records that have <code>CTO_REVIEWED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCtoReviewedBy(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CTO_REVIEWED_BY, values);
    }

    /**
     * Fetch records that have <code>CTO_REVIEWED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCtoReviewedAt(Timestamp... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CTO_REVIEWED_AT, values);
    }

    /**
     * Fetch records that have <code>LSD_REMARKS IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByLsdRemarks(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.LSD_REMARKS, values);
    }

    /**
     * Fetch records that have <code>LSD_REVIEWED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByLsdReviewedBy(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.LSD_REVIEWED_BY, values);
    }

    /**
     * Fetch records that have <code>LSD_REVIEWED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByLsdReviewedAt(Timestamp... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.LSD_REVIEWED_AT, values);
    }

    /**
     * Fetch records that have <code>UPDATED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByUpdatedBy(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.UPDATED_BY, values);
    }

    /**
     * Fetch records that have <code>UPDATED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByUpdatedAt(Timestamp... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>CREATED_BY IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCreatedBy(String... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>CREATED_AT IN (values)</code>
     */
    public List<com.test.springboot.jooq.data.jooq.tables.pojos.CtmsCompany> fetchByCreatedAt(Timestamp... values) {
        return fetch(CtmsCompany.CTMS_COMPANY.CREATED_AT, values);
    }
}
