/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUser implements Serializable {

    private static final long serialVersionUID = 1253787373;

    private BigInteger id;
    private String     loginId;
    private String     email;
    private Byte       isSubmitter;
    private Byte       isCto;
    private Byte       isLsd;
    private Byte       isAdmin;
    private String     updatedBy;
    private Timestamp  updatedAt;

    public CtmsUser() {}

    public CtmsUser(CtmsUser value) {
        this.id = value.id;
        this.loginId = value.loginId;
        this.email = value.email;
        this.isSubmitter = value.isSubmitter;
        this.isCto = value.isCto;
        this.isLsd = value.isLsd;
        this.isAdmin = value.isAdmin;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
    }

    public CtmsUser(
        BigInteger id,
        String     loginId,
        String     email,
        Byte       isSubmitter,
        Byte       isCto,
        Byte       isLsd,
        Byte       isAdmin,
        String     updatedBy,
        Timestamp  updatedAt
    ) {
        this.id = id;
        this.loginId = loginId;
        this.email = email;
        this.isSubmitter = isSubmitter;
        this.isCto = isCto;
        this.isLsd = isLsd;
        this.isAdmin = isAdmin;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getLoginId() {
        return this.loginId;
    }

    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Byte getIsSubmitter() {
        return this.isSubmitter;
    }

    public void setIsSubmitter(Byte isSubmitter) {
        this.isSubmitter = isSubmitter;
    }

    public Byte getIsCto() {
        return this.isCto;
    }

    public void setIsCto(Byte isCto) {
        this.isCto = isCto;
    }

    public Byte getIsLsd() {
        return this.isLsd;
    }

    public void setIsLsd(Byte isLsd) {
        this.isLsd = isLsd;
    }

    public Byte getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsUser (");

        sb.append(id);
        sb.append(", ").append(loginId);
        sb.append(", ").append(email);
        sb.append(", ").append(isSubmitter);
        sb.append(", ").append(isCto);
        sb.append(", ").append(isLsd);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
