/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyName implements Serializable {

    private static final long serialVersionUID = 1505204609;

    private BigInteger id;
    private BigInteger companyId;
    private String     englishName;
    private String     chineseName;

    public CtmsCompanyName() {}

    public CtmsCompanyName(CtmsCompanyName value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.englishName = value.englishName;
        this.chineseName = value.chineseName;
    }

    public CtmsCompanyName(
        BigInteger id,
        BigInteger companyId,
        String     englishName,
        String     chineseName
    ) {
        this.id = id;
        this.companyId = companyId;
        this.englishName = englishName;
        this.chineseName = chineseName;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    public String getEnglishName() {
        return this.englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getChineseName() {
        return this.chineseName;
    }

    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCompanyName (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(englishName);
        sb.append(", ").append(chineseName);

        sb.append(")");
        return sb.toString();
    }
}
