/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsReportGrpHier implements Serializable {

    private static final long serialVersionUID = -812714496;

    private BigInteger id;
    private String     name;
    private String     code;
    private BigInteger parentId;
    private Long       displaySeq;

    public CtmsReportGrpHier() {}

    public CtmsReportGrpHier(CtmsReportGrpHier value) {
        this.id = value.id;
        this.name = value.name;
        this.code = value.code;
        this.parentId = value.parentId;
        this.displaySeq = value.displaySeq;
    }

    public CtmsReportGrpHier(
        BigInteger id,
        String     name,
        String     code,
        BigInteger parentId,
        Long       displaySeq
    ) {
        this.id = id;
        this.name = name;
        this.code = code;
        this.parentId = parentId;
        this.displaySeq = displaySeq;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public BigInteger getParentId() {
        return this.parentId;
    }

    public void setParentId(BigInteger parentId) {
        this.parentId = parentId;
    }

    public Long getDisplaySeq() {
        return this.displaySeq;
    }

    public void setDisplaySeq(Long displaySeq) {
        this.displaySeq = displaySeq;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsReportGrpHier (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(code);
        sb.append(", ").append(parentId);
        sb.append(", ").append(displaySeq);

        sb.append(")");
        return sb.toString();
    }
}
