/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormOtherPty implements Serializable {

    private static final long serialVersionUID = 1319545900;

    private BigInteger id;
    private BigInteger ctFormId;
    private String     companyName;

    public CtmsCtFormOtherPty() {}

    public CtmsCtFormOtherPty(CtmsCtFormOtherPty value) {
        this.id = value.id;
        this.ctFormId = value.ctFormId;
        this.companyName = value.companyName;
    }

    public CtmsCtFormOtherPty(
        BigInteger id,
        BigInteger ctFormId,
        String     companyName
    ) {
        this.id = id;
        this.ctFormId = ctFormId;
        this.companyName = companyName;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCtFormId() {
        return this.ctFormId;
    }

    public void setCtFormId(BigInteger ctFormId) {
        this.ctFormId = ctFormId;
    }

    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCtFormOtherPty (");

        sb.append(id);
        sb.append(", ").append(ctFormId);
        sb.append(", ").append(companyName);

        sb.append(")");
        return sb.toString();
    }
}
