/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsAuditChecklist implements Serializable {

    private static final long serialVersionUID = -2056973748;

    private BigInteger id;
    private String     rptUserGrpLv1;
    private String     rptUserGrpLv2;
    private String     rptUserGrpLv3;
    private String     ctoEndorserGrp;
    private String     period;
    private Byte       hasChanges;
    private Byte       hasUnreported;
    private Byte       isAwarePotential;
    private String     status;
    private String     reportedBy;
    private Timestamp  reportedAt;
    private String     remarks;
    private String     ctoRemarks;
    private String     ctoReviewedBy;
    private Timestamp  ctoReviewedAt;
    private String     lsdRemarks;
    private String     lsdReviewedBy;
    private Timestamp  lsdReviewedAt;
    private String     updatedBy;
    private Timestamp  updatedAt;
    private Timestamp  createdAt;

    public CtmsAuditChecklist() {}

    public CtmsAuditChecklist(CtmsAuditChecklist value) {
        this.id = value.id;
        this.rptUserGrpLv1 = value.rptUserGrpLv1;
        this.rptUserGrpLv2 = value.rptUserGrpLv2;
        this.rptUserGrpLv3 = value.rptUserGrpLv3;
        this.ctoEndorserGrp = value.ctoEndorserGrp;
        this.period = value.period;
        this.hasChanges = value.hasChanges;
        this.hasUnreported = value.hasUnreported;
        this.isAwarePotential = value.isAwarePotential;
        this.status = value.status;
        this.reportedBy = value.reportedBy;
        this.reportedAt = value.reportedAt;
        this.remarks = value.remarks;
        this.ctoRemarks = value.ctoRemarks;
        this.ctoReviewedBy = value.ctoReviewedBy;
        this.ctoReviewedAt = value.ctoReviewedAt;
        this.lsdRemarks = value.lsdRemarks;
        this.lsdReviewedBy = value.lsdReviewedBy;
        this.lsdReviewedAt = value.lsdReviewedAt;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
        this.createdAt = value.createdAt;
    }

    public CtmsAuditChecklist(
        BigInteger id,
        String     rptUserGrpLv1,
        String     rptUserGrpLv2,
        String     rptUserGrpLv3,
        String     ctoEndorserGrp,
        String     period,
        Byte       hasChanges,
        Byte       hasUnreported,
        Byte       isAwarePotential,
        String     status,
        String     reportedBy,
        Timestamp  reportedAt,
        String     remarks,
        String     ctoRemarks,
        String     ctoReviewedBy,
        Timestamp  ctoReviewedAt,
        String     lsdRemarks,
        String     lsdReviewedBy,
        Timestamp  lsdReviewedAt,
        String     updatedBy,
        Timestamp  updatedAt,
        Timestamp  createdAt
    ) {
        this.id = id;
        this.rptUserGrpLv1 = rptUserGrpLv1;
        this.rptUserGrpLv2 = rptUserGrpLv2;
        this.rptUserGrpLv3 = rptUserGrpLv3;
        this.ctoEndorserGrp = ctoEndorserGrp;
        this.period = period;
        this.hasChanges = hasChanges;
        this.hasUnreported = hasUnreported;
        this.isAwarePotential = isAwarePotential;
        this.status = status;
        this.reportedBy = reportedBy;
        this.reportedAt = reportedAt;
        this.remarks = remarks;
        this.ctoRemarks = ctoRemarks;
        this.ctoReviewedBy = ctoReviewedBy;
        this.ctoReviewedAt = ctoReviewedAt;
        this.lsdRemarks = lsdRemarks;
        this.lsdReviewedBy = lsdReviewedBy;
        this.lsdReviewedAt = lsdReviewedAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getRptUserGrpLv1() {
        return this.rptUserGrpLv1;
    }

    public void setRptUserGrpLv1(String rptUserGrpLv1) {
        this.rptUserGrpLv1 = rptUserGrpLv1;
    }

    public String getRptUserGrpLv2() {
        return this.rptUserGrpLv2;
    }

    public void setRptUserGrpLv2(String rptUserGrpLv2) {
        this.rptUserGrpLv2 = rptUserGrpLv2;
    }

    public String getRptUserGrpLv3() {
        return this.rptUserGrpLv3;
    }

    public void setRptUserGrpLv3(String rptUserGrpLv3) {
        this.rptUserGrpLv3 = rptUserGrpLv3;
    }

    public String getCtoEndorserGrp() {
        return this.ctoEndorserGrp;
    }

    public void setCtoEndorserGrp(String ctoEndorserGrp) {
        this.ctoEndorserGrp = ctoEndorserGrp;
    }

    public String getPeriod() {
        return this.period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public Byte getHasChanges() {
        return this.hasChanges;
    }

    public void setHasChanges(Byte hasChanges) {
        this.hasChanges = hasChanges;
    }

    public Byte getHasUnreported() {
        return this.hasUnreported;
    }

    public void setHasUnreported(Byte hasUnreported) {
        this.hasUnreported = hasUnreported;
    }

    public Byte getIsAwarePotential() {
        return this.isAwarePotential;
    }

    public void setIsAwarePotential(Byte isAwarePotential) {
        this.isAwarePotential = isAwarePotential;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getReportedBy() {
        return this.reportedBy;
    }

    public void setReportedBy(String reportedBy) {
        this.reportedBy = reportedBy;
    }

    public Timestamp getReportedAt() {
        return this.reportedAt;
    }

    public void setReportedAt(Timestamp reportedAt) {
        this.reportedAt = reportedAt;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCtoRemarks() {
        return this.ctoRemarks;
    }

    public void setCtoRemarks(String ctoRemarks) {
        this.ctoRemarks = ctoRemarks;
    }

    public String getCtoReviewedBy() {
        return this.ctoReviewedBy;
    }

    public void setCtoReviewedBy(String ctoReviewedBy) {
        this.ctoReviewedBy = ctoReviewedBy;
    }

    public Timestamp getCtoReviewedAt() {
        return this.ctoReviewedAt;
    }

    public void setCtoReviewedAt(Timestamp ctoReviewedAt) {
        this.ctoReviewedAt = ctoReviewedAt;
    }

    public String getLsdRemarks() {
        return this.lsdRemarks;
    }

    public void setLsdRemarks(String lsdRemarks) {
        this.lsdRemarks = lsdRemarks;
    }

    public String getLsdReviewedBy() {
        return this.lsdReviewedBy;
    }

    public void setLsdReviewedBy(String lsdReviewedBy) {
        this.lsdReviewedBy = lsdReviewedBy;
    }

    public Timestamp getLsdReviewedAt() {
        return this.lsdReviewedAt;
    }

    public void setLsdReviewedAt(Timestamp lsdReviewedAt) {
        this.lsdReviewedAt = lsdReviewedAt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsAuditChecklist (");

        sb.append(id);
        sb.append(", ").append(rptUserGrpLv1);
        sb.append(", ").append(rptUserGrpLv2);
        sb.append(", ").append(rptUserGrpLv3);
        sb.append(", ").append(ctoEndorserGrp);
        sb.append(", ").append(period);
        sb.append(", ").append(hasChanges);
        sb.append(", ").append(hasUnreported);
        sb.append(", ").append(isAwarePotential);
        sb.append(", ").append(status);
        sb.append(", ").append(reportedBy);
        sb.append(", ").append(reportedAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(ctoRemarks);
        sb.append(", ").append(ctoReviewedBy);
        sb.append(", ").append(ctoReviewedAt);
        sb.append(", ").append(lsdRemarks);
        sb.append(", ").append(lsdReviewedBy);
        sb.append(", ").append(lsdReviewedAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
