/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormPty implements Serializable {

    private static final long serialVersionUID = -602965398;

    private BigInteger id;
    private BigInteger ctFormId;
    private BigInteger companyId;
    private String     companyCode;
    private String     companyGrpCode;
    private String     englishName;
    private String     chineseName;

    public CtmsCtFormPty() {}

    public CtmsCtFormPty(CtmsCtFormPty value) {
        this.id = value.id;
        this.ctFormId = value.ctFormId;
        this.companyId = value.companyId;
        this.companyCode = value.companyCode;
        this.companyGrpCode = value.companyGrpCode;
        this.englishName = value.englishName;
        this.chineseName = value.chineseName;
    }

    public CtmsCtFormPty(
        BigInteger id,
        BigInteger ctFormId,
        BigInteger companyId,
        String     companyCode,
        String     companyGrpCode,
        String     englishName,
        String     chineseName
    ) {
        this.id = id;
        this.ctFormId = ctFormId;
        this.companyId = companyId;
        this.companyCode = companyCode;
        this.companyGrpCode = companyGrpCode;
        this.englishName = englishName;
        this.chineseName = chineseName;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCtFormId() {
        return this.ctFormId;
    }

    public void setCtFormId(BigInteger ctFormId) {
        this.ctFormId = ctFormId;
    }

    public BigInteger getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(BigInteger companyId) {
        this.companyId = companyId;
    }

    public String getCompanyCode() {
        return this.companyCode;
    }

    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    public String getCompanyGrpCode() {
        return this.companyGrpCode;
    }

    public void setCompanyGrpCode(String companyGrpCode) {
        this.companyGrpCode = companyGrpCode;
    }

    public String getEnglishName() {
        return this.englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getChineseName() {
        return this.chineseName;
    }

    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCtFormPty (");

        sb.append(id);
        sb.append(", ").append(ctFormId);
        sb.append(", ").append(companyId);
        sb.append(", ").append(companyCode);
        sb.append(", ").append(companyGrpCode);
        sb.append(", ").append(englishName);
        sb.append(", ").append(chineseName);

        sb.append(")");
        return sb.toString();
    }
}
