/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompany implements Serializable {

    private static final long serialVersionUID = -1135527141;

    private BigInteger id;
    private String     code;
    private String     englishName;
    private String     chineseName;
    private BigInteger companyCatId;
    private String     brNumber;
    private String     address;
    private String     phoneNumber;
    private String     status;
    private BigInteger companyGrpId;
    private String     requestedBy;
    private Timestamp  requestedAt;
    private String     remarks;
    private String     ctoRemarks;
    private String     ctoReviewedBy;
    private Timestamp  ctoReviewedAt;
    private String     lsdRemarks;
    private String     lsdReviewedBy;
    private Timestamp  lsdReviewedAt;
    private String     updatedBy;
    private Timestamp  updatedAt;
    private String     createdBy;
    private Timestamp  createdAt;

    public CtmsCompany() {}

    public CtmsCompany(CtmsCompany value) {
        this.id = value.id;
        this.code = value.code;
        this.englishName = value.englishName;
        this.chineseName = value.chineseName;
        this.companyCatId = value.companyCatId;
        this.brNumber = value.brNumber;
        this.address = value.address;
        this.phoneNumber = value.phoneNumber;
        this.status = value.status;
        this.companyGrpId = value.companyGrpId;
        this.requestedBy = value.requestedBy;
        this.requestedAt = value.requestedAt;
        this.remarks = value.remarks;
        this.ctoRemarks = value.ctoRemarks;
        this.ctoReviewedBy = value.ctoReviewedBy;
        this.ctoReviewedAt = value.ctoReviewedAt;
        this.lsdRemarks = value.lsdRemarks;
        this.lsdReviewedBy = value.lsdReviewedBy;
        this.lsdReviewedAt = value.lsdReviewedAt;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
    }

    public CtmsCompany(
        BigInteger id,
        String     code,
        String     englishName,
        String     chineseName,
        BigInteger companyCatId,
        String     brNumber,
        String     address,
        String     phoneNumber,
        String     status,
        BigInteger companyGrpId,
        String     requestedBy,
        Timestamp  requestedAt,
        String     remarks,
        String     ctoRemarks,
        String     ctoReviewedBy,
        Timestamp  ctoReviewedAt,
        String     lsdRemarks,
        String     lsdReviewedBy,
        Timestamp  lsdReviewedAt,
        String     updatedBy,
        Timestamp  updatedAt,
        String     createdBy,
        Timestamp  createdAt
    ) {
        this.id = id;
        this.code = code;
        this.englishName = englishName;
        this.chineseName = chineseName;
        this.companyCatId = companyCatId;
        this.brNumber = brNumber;
        this.address = address;
        this.phoneNumber = phoneNumber;
        this.status = status;
        this.companyGrpId = companyGrpId;
        this.requestedBy = requestedBy;
        this.requestedAt = requestedAt;
        this.remarks = remarks;
        this.ctoRemarks = ctoRemarks;
        this.ctoReviewedBy = ctoReviewedBy;
        this.ctoReviewedAt = ctoReviewedAt;
        this.lsdRemarks = lsdRemarks;
        this.lsdReviewedBy = lsdReviewedBy;
        this.lsdReviewedAt = lsdReviewedAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getEnglishName() {
        return this.englishName;
    }

    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    public String getChineseName() {
        return this.chineseName;
    }

    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    public BigInteger getCompanyCatId() {
        return this.companyCatId;
    }

    public void setCompanyCatId(BigInteger companyCatId) {
        this.companyCatId = companyCatId;
    }

    public String getBrNumber() {
        return this.brNumber;
    }

    public void setBrNumber(String brNumber) {
        this.brNumber = brNumber;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BigInteger getCompanyGrpId() {
        return this.companyGrpId;
    }

    public void setCompanyGrpId(BigInteger companyGrpId) {
        this.companyGrpId = companyGrpId;
    }

    public String getRequestedBy() {
        return this.requestedBy;
    }

    public void setRequestedBy(String requestedBy) {
        this.requestedBy = requestedBy;
    }

    public Timestamp getRequestedAt() {
        return this.requestedAt;
    }

    public void setRequestedAt(Timestamp requestedAt) {
        this.requestedAt = requestedAt;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCtoRemarks() {
        return this.ctoRemarks;
    }

    public void setCtoRemarks(String ctoRemarks) {
        this.ctoRemarks = ctoRemarks;
    }

    public String getCtoReviewedBy() {
        return this.ctoReviewedBy;
    }

    public void setCtoReviewedBy(String ctoReviewedBy) {
        this.ctoReviewedBy = ctoReviewedBy;
    }

    public Timestamp getCtoReviewedAt() {
        return this.ctoReviewedAt;
    }

    public void setCtoReviewedAt(Timestamp ctoReviewedAt) {
        this.ctoReviewedAt = ctoReviewedAt;
    }

    public String getLsdRemarks() {
        return this.lsdRemarks;
    }

    public void setLsdRemarks(String lsdRemarks) {
        this.lsdRemarks = lsdRemarks;
    }

    public String getLsdReviewedBy() {
        return this.lsdReviewedBy;
    }

    public void setLsdReviewedBy(String lsdReviewedBy) {
        this.lsdReviewedBy = lsdReviewedBy;
    }

    public Timestamp getLsdReviewedAt() {
        return this.lsdReviewedAt;
    }

    public void setLsdReviewedAt(Timestamp lsdReviewedAt) {
        this.lsdReviewedAt = lsdReviewedAt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCompany (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(englishName);
        sb.append(", ").append(chineseName);
        sb.append(", ").append(companyCatId);
        sb.append(", ").append(brNumber);
        sb.append(", ").append(address);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(status);
        sb.append(", ").append(companyGrpId);
        sb.append(", ").append(requestedBy);
        sb.append(", ").append(requestedAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(ctoRemarks);
        sb.append(", ").append(ctoReviewedBy);
        sb.append(", ").append(ctoReviewedAt);
        sb.append(", ").append(lsdRemarks);
        sb.append(", ").append(lsdReviewedBy);
        sb.append(", ").append(lsdReviewedAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
