/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUserPreference implements Serializable {

    private static final long serialVersionUID = 356678939;

    private BigInteger id;
    private String     defaultRptUserGrpLv1;
    private String     defaultRptUserGrpLv2;
    private String     defaultRptUserGrpLv3;
    private String     updatedBy;
    private Timestamp  updatedAt;

    public CtmsUserPreference() {}

    public CtmsUserPreference(CtmsUserPreference value) {
        this.id = value.id;
        this.defaultRptUserGrpLv1 = value.defaultRptUserGrpLv1;
        this.defaultRptUserGrpLv2 = value.defaultRptUserGrpLv2;
        this.defaultRptUserGrpLv3 = value.defaultRptUserGrpLv3;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
    }

    public CtmsUserPreference(
        BigInteger id,
        String     defaultRptUserGrpLv1,
        String     defaultRptUserGrpLv2,
        String     defaultRptUserGrpLv3,
        String     updatedBy,
        Timestamp  updatedAt
    ) {
        this.id = id;
        this.defaultRptUserGrpLv1 = defaultRptUserGrpLv1;
        this.defaultRptUserGrpLv2 = defaultRptUserGrpLv2;
        this.defaultRptUserGrpLv3 = defaultRptUserGrpLv3;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getDefaultRptUserGrpLv1() {
        return this.defaultRptUserGrpLv1;
    }

    public void setDefaultRptUserGrpLv1(String defaultRptUserGrpLv1) {
        this.defaultRptUserGrpLv1 = defaultRptUserGrpLv1;
    }

    public String getDefaultRptUserGrpLv2() {
        return this.defaultRptUserGrpLv2;
    }

    public void setDefaultRptUserGrpLv2(String defaultRptUserGrpLv2) {
        this.defaultRptUserGrpLv2 = defaultRptUserGrpLv2;
    }

    public String getDefaultRptUserGrpLv3() {
        return this.defaultRptUserGrpLv3;
    }

    public void setDefaultRptUserGrpLv3(String defaultRptUserGrpLv3) {
        this.defaultRptUserGrpLv3 = defaultRptUserGrpLv3;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsUserPreference (");

        sb.append(id);
        sb.append(", ").append(defaultRptUserGrpLv1);
        sb.append(", ").append(defaultRptUserGrpLv2);
        sb.append(", ").append(defaultRptUserGrpLv3);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
