/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigInteger;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormAgmtFiles implements Serializable {

    private static final long serialVersionUID = -396594308;

    private BigInteger id;
    private BigInteger ctFormId;
    private String     name;
    private byte[]     content;

    public CtmsCtFormAgmtFiles() {}

    public CtmsCtFormAgmtFiles(CtmsCtFormAgmtFiles value) {
        this.id = value.id;
        this.ctFormId = value.ctFormId;
        this.name = value.name;
        this.content = value.content;
    }

    public CtmsCtFormAgmtFiles(
        BigInteger id,
        BigInteger ctFormId,
        String     name,
        byte[]     content
    ) {
        this.id = id;
        this.ctFormId = ctFormId;
        this.name = name;
        this.content = content;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCtFormId() {
        return this.ctFormId;
    }

    public void setCtFormId(BigInteger ctFormId) {
        this.ctFormId = ctFormId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getContent() {
        return this.content;
    }

    public void setContent(byte... content) {
        this.content = content;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCtFormAgmtFiles (");

        sb.append(id);
        sb.append(", ").append(ctFormId);
        sb.append(", ").append(name);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
