/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtForm implements Serializable {

    private static final long serialVersionUID = 1706664746;

    private BigInteger id;
    private BigInteger copiedFromId;
    private String     rptUserGrpLv1;
    private String     rptUserGrpLv2;
    private String     rptUserGrpLv3;
    private String     ctoEndorserGrp;
    private String     transactionType;
    private Byte       hasAgmt;
    private String     agmtName;
    private Date       agmtSignDate;
    private String     agmtDurationType;
    private Date       agmtStartDate;
    private Date       agmtEndDate;
    private String     agmtAutoRenewUnit;
    private BigDecimal agmtAutoRenew;
    private String     pricingTerm;
    private String     pricingBasis;
    private BigDecimal projectedAnnualPayment;
    private BigDecimal projectedAnnualReceive;
    private Byte       isUnknownSmallAp;
    private Byte       isUnknownSmallAr;
    private String     status;
    private Byte       isArchived;
    private String     reportedBy;
    private Timestamp  reportedAt;
    private String     remarks;
    private String     ctoRemarks;
    private String     ctoReviewedBy;
    private Timestamp  ctoReviewedAt;
    private String     lsdRemarks;
    private String     lsdReviewedBy;
    private Timestamp  lsdReviewedAt;
    private Timestamp  createdAt;
    private String     updatedBy;
    private Timestamp  updatedAt;

    public CtmsCtForm() {}

    public CtmsCtForm(CtmsCtForm value) {
        this.id = value.id;
        this.copiedFromId = value.copiedFromId;
        this.rptUserGrpLv1 = value.rptUserGrpLv1;
        this.rptUserGrpLv2 = value.rptUserGrpLv2;
        this.rptUserGrpLv3 = value.rptUserGrpLv3;
        this.ctoEndorserGrp = value.ctoEndorserGrp;
        this.transactionType = value.transactionType;
        this.hasAgmt = value.hasAgmt;
        this.agmtName = value.agmtName;
        this.agmtSignDate = value.agmtSignDate;
        this.agmtDurationType = value.agmtDurationType;
        this.agmtStartDate = value.agmtStartDate;
        this.agmtEndDate = value.agmtEndDate;
        this.agmtAutoRenewUnit = value.agmtAutoRenewUnit;
        this.agmtAutoRenew = value.agmtAutoRenew;
        this.pricingTerm = value.pricingTerm;
        this.pricingBasis = value.pricingBasis;
        this.projectedAnnualPayment = value.projectedAnnualPayment;
        this.projectedAnnualReceive = value.projectedAnnualReceive;
        this.isUnknownSmallAp = value.isUnknownSmallAp;
        this.isUnknownSmallAr = value.isUnknownSmallAr;
        this.status = value.status;
        this.isArchived = value.isArchived;
        this.reportedBy = value.reportedBy;
        this.reportedAt = value.reportedAt;
        this.remarks = value.remarks;
        this.ctoRemarks = value.ctoRemarks;
        this.ctoReviewedBy = value.ctoReviewedBy;
        this.ctoReviewedAt = value.ctoReviewedAt;
        this.lsdRemarks = value.lsdRemarks;
        this.lsdReviewedBy = value.lsdReviewedBy;
        this.lsdReviewedAt = value.lsdReviewedAt;
        this.createdAt = value.createdAt;
        this.updatedBy = value.updatedBy;
        this.updatedAt = value.updatedAt;
    }

    public CtmsCtForm(
        BigInteger id,
        BigInteger copiedFromId,
        String     rptUserGrpLv1,
        String     rptUserGrpLv2,
        String     rptUserGrpLv3,
        String     ctoEndorserGrp,
        String     transactionType,
        Byte       hasAgmt,
        String     agmtName,
        Date       agmtSignDate,
        String     agmtDurationType,
        Date       agmtStartDate,
        Date       agmtEndDate,
        String     agmtAutoRenewUnit,
        BigDecimal agmtAutoRenew,
        String     pricingTerm,
        String     pricingBasis,
        BigDecimal projectedAnnualPayment,
        BigDecimal projectedAnnualReceive,
        Byte       isUnknownSmallAp,
        Byte       isUnknownSmallAr,
        String     status,
        Byte       isArchived,
        String     reportedBy,
        Timestamp  reportedAt,
        String     remarks,
        String     ctoRemarks,
        String     ctoReviewedBy,
        Timestamp  ctoReviewedAt,
        String     lsdRemarks,
        String     lsdReviewedBy,
        Timestamp  lsdReviewedAt,
        Timestamp  createdAt,
        String     updatedBy,
        Timestamp  updatedAt
    ) {
        this.id = id;
        this.copiedFromId = copiedFromId;
        this.rptUserGrpLv1 = rptUserGrpLv1;
        this.rptUserGrpLv2 = rptUserGrpLv2;
        this.rptUserGrpLv3 = rptUserGrpLv3;
        this.ctoEndorserGrp = ctoEndorserGrp;
        this.transactionType = transactionType;
        this.hasAgmt = hasAgmt;
        this.agmtName = agmtName;
        this.agmtSignDate = agmtSignDate;
        this.agmtDurationType = agmtDurationType;
        this.agmtStartDate = agmtStartDate;
        this.agmtEndDate = agmtEndDate;
        this.agmtAutoRenewUnit = agmtAutoRenewUnit;
        this.agmtAutoRenew = agmtAutoRenew;
        this.pricingTerm = pricingTerm;
        this.pricingBasis = pricingBasis;
        this.projectedAnnualPayment = projectedAnnualPayment;
        this.projectedAnnualReceive = projectedAnnualReceive;
        this.isUnknownSmallAp = isUnknownSmallAp;
        this.isUnknownSmallAr = isUnknownSmallAr;
        this.status = status;
        this.isArchived = isArchived;
        this.reportedBy = reportedBy;
        this.reportedAt = reportedAt;
        this.remarks = remarks;
        this.ctoRemarks = ctoRemarks;
        this.ctoReviewedBy = ctoReviewedBy;
        this.ctoReviewedAt = ctoReviewedAt;
        this.lsdRemarks = lsdRemarks;
        this.lsdReviewedBy = lsdReviewedBy;
        this.lsdReviewedAt = lsdReviewedAt;
        this.createdAt = createdAt;
        this.updatedBy = updatedBy;
        this.updatedAt = updatedAt;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public BigInteger getCopiedFromId() {
        return this.copiedFromId;
    }

    public void setCopiedFromId(BigInteger copiedFromId) {
        this.copiedFromId = copiedFromId;
    }

    public String getRptUserGrpLv1() {
        return this.rptUserGrpLv1;
    }

    public void setRptUserGrpLv1(String rptUserGrpLv1) {
        this.rptUserGrpLv1 = rptUserGrpLv1;
    }

    public String getRptUserGrpLv2() {
        return this.rptUserGrpLv2;
    }

    public void setRptUserGrpLv2(String rptUserGrpLv2) {
        this.rptUserGrpLv2 = rptUserGrpLv2;
    }

    public String getRptUserGrpLv3() {
        return this.rptUserGrpLv3;
    }

    public void setRptUserGrpLv3(String rptUserGrpLv3) {
        this.rptUserGrpLv3 = rptUserGrpLv3;
    }

    public String getCtoEndorserGrp() {
        return this.ctoEndorserGrp;
    }

    public void setCtoEndorserGrp(String ctoEndorserGrp) {
        this.ctoEndorserGrp = ctoEndorserGrp;
    }

    public String getTransactionType() {
        return this.transactionType;
    }

    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    public Byte getHasAgmt() {
        return this.hasAgmt;
    }

    public void setHasAgmt(Byte hasAgmt) {
        this.hasAgmt = hasAgmt;
    }

    public String getAgmtName() {
        return this.agmtName;
    }

    public void setAgmtName(String agmtName) {
        this.agmtName = agmtName;
    }

    public Date getAgmtSignDate() {
        return this.agmtSignDate;
    }

    public void setAgmtSignDate(Date agmtSignDate) {
        this.agmtSignDate = agmtSignDate;
    }

    public String getAgmtDurationType() {
        return this.agmtDurationType;
    }

    public void setAgmtDurationType(String agmtDurationType) {
        this.agmtDurationType = agmtDurationType;
    }

    public Date getAgmtStartDate() {
        return this.agmtStartDate;
    }

    public void setAgmtStartDate(Date agmtStartDate) {
        this.agmtStartDate = agmtStartDate;
    }

    public Date getAgmtEndDate() {
        return this.agmtEndDate;
    }

    public void setAgmtEndDate(Date agmtEndDate) {
        this.agmtEndDate = agmtEndDate;
    }

    public String getAgmtAutoRenewUnit() {
        return this.agmtAutoRenewUnit;
    }

    public void setAgmtAutoRenewUnit(String agmtAutoRenewUnit) {
        this.agmtAutoRenewUnit = agmtAutoRenewUnit;
    }

    public BigDecimal getAgmtAutoRenew() {
        return this.agmtAutoRenew;
    }

    public void setAgmtAutoRenew(BigDecimal agmtAutoRenew) {
        this.agmtAutoRenew = agmtAutoRenew;
    }

    public String getPricingTerm() {
        return this.pricingTerm;
    }

    public void setPricingTerm(String pricingTerm) {
        this.pricingTerm = pricingTerm;
    }

    public String getPricingBasis() {
        return this.pricingBasis;
    }

    public void setPricingBasis(String pricingBasis) {
        this.pricingBasis = pricingBasis;
    }

    public BigDecimal getProjectedAnnualPayment() {
        return this.projectedAnnualPayment;
    }

    public void setProjectedAnnualPayment(BigDecimal projectedAnnualPayment) {
        this.projectedAnnualPayment = projectedAnnualPayment;
    }

    public BigDecimal getProjectedAnnualReceive() {
        return this.projectedAnnualReceive;
    }

    public void setProjectedAnnualReceive(BigDecimal projectedAnnualReceive) {
        this.projectedAnnualReceive = projectedAnnualReceive;
    }

    public Byte getIsUnknownSmallAp() {
        return this.isUnknownSmallAp;
    }

    public void setIsUnknownSmallAp(Byte isUnknownSmallAp) {
        this.isUnknownSmallAp = isUnknownSmallAp;
    }

    public Byte getIsUnknownSmallAr() {
        return this.isUnknownSmallAr;
    }

    public void setIsUnknownSmallAr(Byte isUnknownSmallAr) {
        this.isUnknownSmallAr = isUnknownSmallAr;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Byte getIsArchived() {
        return this.isArchived;
    }

    public void setIsArchived(Byte isArchived) {
        this.isArchived = isArchived;
    }

    public String getReportedBy() {
        return this.reportedBy;
    }

    public void setReportedBy(String reportedBy) {
        this.reportedBy = reportedBy;
    }

    public Timestamp getReportedAt() {
        return this.reportedAt;
    }

    public void setReportedAt(Timestamp reportedAt) {
        this.reportedAt = reportedAt;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getCtoRemarks() {
        return this.ctoRemarks;
    }

    public void setCtoRemarks(String ctoRemarks) {
        this.ctoRemarks = ctoRemarks;
    }

    public String getCtoReviewedBy() {
        return this.ctoReviewedBy;
    }

    public void setCtoReviewedBy(String ctoReviewedBy) {
        this.ctoReviewedBy = ctoReviewedBy;
    }

    public Timestamp getCtoReviewedAt() {
        return this.ctoReviewedAt;
    }

    public void setCtoReviewedAt(Timestamp ctoReviewedAt) {
        this.ctoReviewedAt = ctoReviewedAt;
    }

    public String getLsdRemarks() {
        return this.lsdRemarks;
    }

    public void setLsdRemarks(String lsdRemarks) {
        this.lsdRemarks = lsdRemarks;
    }

    public String getLsdReviewedBy() {
        return this.lsdReviewedBy;
    }

    public void setLsdReviewedBy(String lsdReviewedBy) {
        this.lsdReviewedBy = lsdReviewedBy;
    }

    public Timestamp getLsdReviewedAt() {
        return this.lsdReviewedAt;
    }

    public void setLsdReviewedAt(Timestamp lsdReviewedAt) {
        this.lsdReviewedAt = lsdReviewedAt;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CtmsCtForm (");

        sb.append(id);
        sb.append(", ").append(copiedFromId);
        sb.append(", ").append(rptUserGrpLv1);
        sb.append(", ").append(rptUserGrpLv2);
        sb.append(", ").append(rptUserGrpLv3);
        sb.append(", ").append(ctoEndorserGrp);
        sb.append(", ").append(transactionType);
        sb.append(", ").append(hasAgmt);
        sb.append(", ").append(agmtName);
        sb.append(", ").append(agmtSignDate);
        sb.append(", ").append(agmtDurationType);
        sb.append(", ").append(agmtStartDate);
        sb.append(", ").append(agmtEndDate);
        sb.append(", ").append(agmtAutoRenewUnit);
        sb.append(", ").append(agmtAutoRenew);
        sb.append(", ").append(pricingTerm);
        sb.append(", ").append(pricingBasis);
        sb.append(", ").append(projectedAnnualPayment);
        sb.append(", ").append(projectedAnnualReceive);
        sb.append(", ").append(isUnknownSmallAp);
        sb.append(", ").append(isUnknownSmallAr);
        sb.append(", ").append(status);
        sb.append(", ").append(isArchived);
        sb.append(", ").append(reportedBy);
        sb.append(", ").append(reportedAt);
        sb.append(", ").append(remarks);
        sb.append(", ").append(ctoRemarks);
        sb.append(", ").append(ctoReviewedBy);
        sb.append(", ").append(ctoReviewedAt);
        sb.append(", ").append(lsdRemarks);
        sb.append(", ").append(lsdReviewedBy);
        sb.append(", ").append(lsdReviewedAt);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
