/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.pojos;


import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.test.springboot.serializer.DateSerializer;

import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@XmlRootElement
public class TestUser implements Serializable {

    private static final long serialVersionUID = 1834935402;

    private BigInteger id;
    private String     username;
    private Short      age;
    private String     phone;
    @JsonSerialize(using = DateSerializer.Serializer.class)
    private Date       birthday;
    private String     email;

    public TestUser() {}

    public TestUser(TestUser value) {
        this.id = value.id;
        this.username = value.username;
        this.age = value.age;
        this.phone = value.phone;
        this.birthday = value.birthday;
        this.email = value.email;
    }

    public TestUser(
        BigInteger id,
        String     username,
        Short      age,
        String     phone,
        Date       birthday,
        String     email
    ) {
        this.id = id;
        this.username = username;
        this.age = age;
        this.phone = phone;
        this.birthday = birthday;
        this.email = email;
    }

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Short getAge() {
        return this.age;
    }

    public void setAge(Short age) {
        this.age = age;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(age);
        sb.append(", ").append(phone);
        sb.append(", ").append(birthday);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
