/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsReportGrpHierRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsReportGrpHier extends TableImpl<CtmsReportGrpHierRecord> {

    private static final long serialVersionUID = -114071210;

    /**
     * The reference instance of <code>PUBLIC.CTMS_REPORT_GRP_HIER</code>
     */
    public static final CtmsReportGrpHier CTMS_REPORT_GRP_HIER = new CtmsReportGrpHier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsReportGrpHierRecord> getRecordType() {
        return CtmsReportGrpHierRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_REPORT_GRP_HIER.ID</code>.
     */
    public final TableField<CtmsReportGrpHierRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_REPORT_GRP_HIER.NAME</code>.
     */
    public final TableField<CtmsReportGrpHierRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>PUBLIC.CTMS_REPORT_GRP_HIER.CODE</code>.
     */
    public final TableField<CtmsReportGrpHierRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_REPORT_GRP_HIER.PARENT_ID</code>.
     */
    public final TableField<CtmsReportGrpHierRecord, BigInteger> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_REPORT_GRP_HIER.DISPLAY_SEQ</code>.
     */
    public final TableField<CtmsReportGrpHierRecord, Long> DISPLAY_SEQ = createField("DISPLAY_SEQ", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_REPORT_GRP_HIER</code> table reference
     */
    public CtmsReportGrpHier() {
        this(DSL.name("CTMS_REPORT_GRP_HIER"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_REPORT_GRP_HIER</code> table reference
     */
    public CtmsReportGrpHier(String alias) {
        this(DSL.name(alias), CTMS_REPORT_GRP_HIER);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_REPORT_GRP_HIER</code> table reference
     */
    public CtmsReportGrpHier(Name alias) {
        this(alias, CTMS_REPORT_GRP_HIER);
    }

    private CtmsReportGrpHier(Name alias, Table<CtmsReportGrpHierRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsReportGrpHier(Name alias, Table<CtmsReportGrpHierRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CTMS_REPORT_GRP_HIER_U01_INDEX_D, Indexes.PRIMARY_KEY_D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsReportGrpHierRecord> getPrimaryKey() {
        return Keys.CTMS_REPORT_GRP_HIER_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsReportGrpHierRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsReportGrpHierRecord>>asList(Keys.CTMS_REPORT_GRP_HIER_PK, Keys.CTMS_REPORT_GRP_HIER_U01);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsReportGrpHier as(String alias) {
        return new CtmsReportGrpHier(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsReportGrpHier as(Name alias) {
        return new CtmsReportGrpHier(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsReportGrpHier rename(String name) {
        return new CtmsReportGrpHier(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsReportGrpHier rename(Name name) {
        return new CtmsReportGrpHier(name, null);
    }
}
