/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyHolderRecord;

import java.math.BigInteger;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyHolder extends TableImpl<CtmsCompanyHolderRecord> {

    private static final long serialVersionUID = 1701434634;

    /**
     * The reference instance of <code>PUBLIC.CTMS_COMPANY_HOLDER</code>
     */
    public static final CtmsCompanyHolder CTMS_COMPANY_HOLDER = new CtmsCompanyHolder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCompanyHolderRecord> getRecordType() {
        return CtmsCompanyHolderRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_HOLDER.ID</code>.
     */
    public final TableField<CtmsCompanyHolderRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_ID</code>.
     */
    public final TableField<CtmsCompanyHolderRecord, BigInteger> COMPANY_ID = createField("COMPANY_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_GRP_ID</code>.
     */
    public final TableField<CtmsCompanyHolderRecord, BigInteger> COMPANY_GRP_ID = createField("COMPANY_GRP_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_HOLDER.START_DATE</code>.
     */
    public final TableField<CtmsCompanyHolderRecord, Date> START_DATE = createField("START_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_HOLDER.END_DATE</code>.
     */
    public final TableField<CtmsCompanyHolderRecord, Date> END_DATE = createField("END_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_COMPANY_HOLDER</code> table reference
     */
    public CtmsCompanyHolder() {
        this(DSL.name("CTMS_COMPANY_HOLDER"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_HOLDER</code> table reference
     */
    public CtmsCompanyHolder(String alias) {
        this(DSL.name(alias), CTMS_COMPANY_HOLDER);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_HOLDER</code> table reference
     */
    public CtmsCompanyHolder(Name alias) {
        this(alias, CTMS_COMPANY_HOLDER);
    }

    private CtmsCompanyHolder(Name alias, Table<CtmsCompanyHolderRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCompanyHolder(Name alias, Table<CtmsCompanyHolderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCompanyHolderRecord> getPrimaryKey() {
        return Keys.CTMS_COMPANY_HOLDER_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCompanyHolderRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCompanyHolderRecord>>asList(Keys.CTMS_COMPANY_HOLDER_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolder as(String alias) {
        return new CtmsCompanyHolder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolder as(Name alias) {
        return new CtmsCompanyHolder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyHolder rename(String name) {
        return new CtmsCompanyHolder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyHolder rename(Name name) {
        return new CtmsCompanyHolder(name, null);
    }
}
