/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyNameRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyName extends TableImpl<CtmsCompanyNameRecord> {

    private static final long serialVersionUID = -769619450;

    /**
     * The reference instance of <code>PUBLIC.CTMS_COMPANY_NAME</code>
     */
    public static final CtmsCompanyName CTMS_COMPANY_NAME = new CtmsCompanyName();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCompanyNameRecord> getRecordType() {
        return CtmsCompanyNameRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_NAME.ID</code>.
     */
    public final TableField<CtmsCompanyNameRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_NAME.COMPANY_ID</code>.
     */
    public final TableField<CtmsCompanyNameRecord, BigInteger> COMPANY_ID = createField("COMPANY_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_NAME.ENGLISH_NAME</code>.
     */
    public final TableField<CtmsCompanyNameRecord, String> ENGLISH_NAME = createField("ENGLISH_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_NAME.CHINESE_NAME</code>.
     */
    public final TableField<CtmsCompanyNameRecord, String> CHINESE_NAME = createField("CHINESE_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * Create a <code>PUBLIC.CTMS_COMPANY_NAME</code> table reference
     */
    public CtmsCompanyName() {
        this(DSL.name("CTMS_COMPANY_NAME"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_NAME</code> table reference
     */
    public CtmsCompanyName(String alias) {
        this(DSL.name(alias), CTMS_COMPANY_NAME);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_NAME</code> table reference
     */
    public CtmsCompanyName(Name alias) {
        this(alias, CTMS_COMPANY_NAME);
    }

    private CtmsCompanyName(Name alias, Table<CtmsCompanyNameRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCompanyName(Name alias, Table<CtmsCompanyNameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_C);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCompanyNameRecord> getPrimaryKey() {
        return Keys.CTMS_COMPANY_NAME_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCompanyNameRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCompanyNameRecord>>asList(Keys.CTMS_COMPANY_NAME_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyName as(String alias) {
        return new CtmsCompanyName(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyName as(Name alias) {
        return new CtmsCompanyName(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyName rename(String name) {
        return new CtmsCompanyName(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyName rename(Name name) {
        return new CtmsCompanyName(name, null);
    }
}
