/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyRequestRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyRequest extends TableImpl<CtmsCompanyRequestRecord> {

    private static final long serialVersionUID = -277358707;

    /**
     * The reference instance of <code>PUBLIC.CTMS_COMPANY_REQUEST</code>
     */
    public static final CtmsCompanyRequest CTMS_COMPANY_REQUEST = new CtmsCompanyRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCompanyRequestRecord> getRecordType() {
        return CtmsCompanyRequestRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.ID</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV1</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> RPT_USER_GRP_LV1 = createField("RPT_USER_GRP_LV1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV2</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> RPT_USER_GRP_LV2 = createField("RPT_USER_GRP_LV2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV3</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> RPT_USER_GRP_LV3 = createField("RPT_USER_GRP_LV3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_ENDORSER_GRP</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> CTO_ENDORSER_GRP = createField("CTO_ENDORSER_GRP", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.ENGLISH_NAME</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> ENGLISH_NAME = createField("ENGLISH_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CHINESE_NAME</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> CHINESE_NAME = createField("CHINESE_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.COMPANY_GRP_ID</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, BigInteger> COMPANY_GRP_ID = createField("COMPANY_GRP_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.BR_NUMBER</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> BR_NUMBER = createField("BR_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.ADDRESS</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.PHONE_NUMBER</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> PHONE_NUMBER = createField("PHONE_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.REMARKS</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.STATUS</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.IS_ARCHIVED</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Byte> IS_ARCHIVED = createField("IS_ARCHIVED", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_BY</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> REQUESTED_BY = createField("REQUESTED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_AT</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Timestamp> REQUESTED_AT = createField("REQUESTED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REMARKS</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> CTO_REMARKS = createField("CTO_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_BY</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> CTO_REVIEWED_BY = createField("CTO_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_AT</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Timestamp> CTO_REVIEWED_AT = createField("CTO_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REMARKS</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> LSD_REMARKS = createField("LSD_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_BY</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> LSD_REVIEWED_BY = createField("LSD_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_AT</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Timestamp> LSD_REVIEWED_AT = createField("LSD_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.CREATED_AT</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_BY</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_AT</code>.
     */
    public final TableField<CtmsCompanyRequestRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_COMPANY_REQUEST</code> table reference
     */
    public CtmsCompanyRequest() {
        this(DSL.name("CTMS_COMPANY_REQUEST"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_REQUEST</code> table reference
     */
    public CtmsCompanyRequest(String alias) {
        this(DSL.name(alias), CTMS_COMPANY_REQUEST);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_REQUEST</code> table reference
     */
    public CtmsCompanyRequest(Name alias) {
        this(alias, CTMS_COMPANY_REQUEST);
    }

    private CtmsCompanyRequest(Name alias, Table<CtmsCompanyRequestRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCompanyRequest(Name alias, Table<CtmsCompanyRequestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCompanyRequestRecord> getPrimaryKey() {
        return Keys.CTMS_COMPANY_REQUEST_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCompanyRequestRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCompanyRequestRecord>>asList(Keys.CTMS_COMPANY_REQUEST_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyRequest as(String alias) {
        return new CtmsCompanyRequest(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyRequest as(Name alias) {
        return new CtmsCompanyRequest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyRequest rename(String name) {
        return new CtmsCompanyRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyRequest rename(Name name) {
        return new CtmsCompanyRequest(name, null);
    }
}
