/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormServiceRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormService extends TableImpl<CtmsCtFormServiceRecord> {

    private static final long serialVersionUID = -2045084933;

    /**
     * The reference instance of <code>PUBLIC.CTMS_CT_FORM_SERVICE</code>
     */
    public static final CtmsCtFormService CTMS_CT_FORM_SERVICE = new CtmsCtFormService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCtFormServiceRecord> getRecordType() {
        return CtmsCtFormServiceRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_SERVICE.ID</code>.
     */
    public final TableField<CtmsCtFormServiceRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_SERVICE.CT_FORM_ID</code>.
     */
    public final TableField<CtmsCtFormServiceRecord, BigInteger> CT_FORM_ID = createField("CT_FORM_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_SERVICE.TYPE_CODE</code>.
     */
    public final TableField<CtmsCtFormServiceRecord, String> TYPE_CODE = createField("TYPE_CODE", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_SERVICE.TYPE_OTHERS</code>.
     */
    public final TableField<CtmsCtFormServiceRecord, String> TYPE_OTHERS = createField("TYPE_OTHERS", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * Create a <code>PUBLIC.CTMS_CT_FORM_SERVICE</code> table reference
     */
    public CtmsCtFormService() {
        this(DSL.name("CTMS_CT_FORM_SERVICE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM_SERVICE</code> table reference
     */
    public CtmsCtFormService(String alias) {
        this(DSL.name(alias), CTMS_CT_FORM_SERVICE);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM_SERVICE</code> table reference
     */
    public CtmsCtFormService(Name alias) {
        this(alias, CTMS_CT_FORM_SERVICE);
    }

    private CtmsCtFormService(Name alias, Table<CtmsCtFormServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCtFormService(Name alias, Table<CtmsCtFormServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CTMS_CT_FORM_SERVICE_U01_INDEX_4, Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCtFormServiceRecord> getPrimaryKey() {
        return Keys.CTMS_CT_FORM_SERVICE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCtFormServiceRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCtFormServiceRecord>>asList(Keys.CTMS_CT_FORM_SERVICE_PK, Keys.CTMS_CT_FORM_SERVICE_U01);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormService as(String alias) {
        return new CtmsCtFormService(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormService as(Name alias) {
        return new CtmsCtFormService(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtFormService rename(String name) {
        return new CtmsCtFormService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtFormService rename(Name name) {
        return new CtmsCtFormService(name, null);
    }
}
