/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserPreferenceRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUserPreference extends TableImpl<CtmsUserPreferenceRecord> {

    private static final long serialVersionUID = -1991252562;

    /**
     * The reference instance of <code>PUBLIC.CTMS_USER_PREFERENCE</code>
     */
    public static final CtmsUserPreference CTMS_USER_PREFERENCE = new CtmsUserPreference();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsUserPreferenceRecord> getRecordType() {
        return CtmsUserPreferenceRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.ID</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV1</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, String> DEFAULT_RPT_USER_GRP_LV1 = createField("DEFAULT_RPT_USER_GRP_LV1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV2</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, String> DEFAULT_RPT_USER_GRP_LV2 = createField("DEFAULT_RPT_USER_GRP_LV2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV3</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, String> DEFAULT_RPT_USER_GRP_LV3 = createField("DEFAULT_RPT_USER_GRP_LV3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_BY</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_AT</code>.
     */
    public final TableField<CtmsUserPreferenceRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_USER_PREFERENCE</code> table reference
     */
    public CtmsUserPreference() {
        this(DSL.name("CTMS_USER_PREFERENCE"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_USER_PREFERENCE</code> table reference
     */
    public CtmsUserPreference(String alias) {
        this(DSL.name(alias), CTMS_USER_PREFERENCE);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_USER_PREFERENCE</code> table reference
     */
    public CtmsUserPreference(Name alias) {
        this(alias, CTMS_USER_PREFERENCE);
    }

    private CtmsUserPreference(Name alias, Table<CtmsUserPreferenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsUserPreference(Name alias, Table<CtmsUserPreferenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_EF);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsUserPreferenceRecord> getPrimaryKey() {
        return Keys.CTMS_USERS_PERFERENCE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsUserPreferenceRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsUserPreferenceRecord>>asList(Keys.CTMS_USERS_PERFERENCE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreference as(String alias) {
        return new CtmsUserPreference(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreference as(Name alias) {
        return new CtmsUserPreference(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsUserPreference rename(String name) {
        return new CtmsUserPreference(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsUserPreference rename(Name name) {
        return new CtmsUserPreference(name, null);
    }
}
