/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserGroupRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUserGroup extends TableImpl<CtmsUserGroupRecord> {

    private static final long serialVersionUID = -605223774;

    /**
     * The reference instance of <code>PUBLIC.CTMS_USER_GROUP</code>
     */
    public static final CtmsUserGroup CTMS_USER_GROUP = new CtmsUserGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsUserGroupRecord> getRecordType() {
        return CtmsUserGroupRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.ID</code>.
     */
    public final TableField<CtmsUserGroupRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.USER_ID</code>.
     */
    public final TableField<CtmsUserGroupRecord, BigInteger> USER_ID = createField("USER_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.GRP_LV1</code>.
     */
    public final TableField<CtmsUserGroupRecord, String> GRP_LV1 = createField("GRP_LV1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.GRP_LV2</code>.
     */
    public final TableField<CtmsUserGroupRecord, String> GRP_LV2 = createField("GRP_LV2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.GRP_LV3</code>.
     */
    public final TableField<CtmsUserGroupRecord, String> GRP_LV3 = createField("GRP_LV3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.UPDATED_BY</code>.
     */
    public final TableField<CtmsUserGroupRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_USER_GROUP.UPDATED_AT</code>.
     */
    public final TableField<CtmsUserGroupRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_USER_GROUP</code> table reference
     */
    public CtmsUserGroup() {
        this(DSL.name("CTMS_USER_GROUP"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_USER_GROUP</code> table reference
     */
    public CtmsUserGroup(String alias) {
        this(DSL.name(alias), CTMS_USER_GROUP);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_USER_GROUP</code> table reference
     */
    public CtmsUserGroup(Name alias) {
        this(alias, CTMS_USER_GROUP);
    }

    private CtmsUserGroup(Name alias, Table<CtmsUserGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsUserGroup(Name alias, Table<CtmsUserGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsUserGroupRecord> getPrimaryKey() {
        return Keys.CTMS_USER_GROUP_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsUserGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsUserGroupRecord>>asList(Keys.CTMS_USER_GROUP_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserGroup as(String alias) {
        return new CtmsUserGroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserGroup as(Name alias) {
        return new CtmsUserGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsUserGroup rename(String name) {
        return new CtmsUserGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsUserGroup rename(Name name) {
        return new CtmsUserGroup(name, null);
    }
}
