/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormRecord;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtForm extends TableImpl<CtmsCtFormRecord> {

    private static final long serialVersionUID = -1589465658;

    /**
     * The reference instance of <code>PUBLIC.CTMS_CT_FORM</code>
     */
    public static final CtmsCtForm CTMS_CT_FORM = new CtmsCtForm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCtFormRecord> getRecordType() {
        return CtmsCtFormRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.ID</code>.
     */
    public final TableField<CtmsCtFormRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.COPIED_FROM_ID</code>.
     */
    public final TableField<CtmsCtFormRecord, BigInteger> COPIED_FROM_ID = createField("COPIED_FROM_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV1</code>.
     */
    public final TableField<CtmsCtFormRecord, String> RPT_USER_GRP_LV1 = createField("RPT_USER_GRP_LV1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV2</code>.
     */
    public final TableField<CtmsCtFormRecord, String> RPT_USER_GRP_LV2 = createField("RPT_USER_GRP_LV2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV3</code>.
     */
    public final TableField<CtmsCtFormRecord, String> RPT_USER_GRP_LV3 = createField("RPT_USER_GRP_LV3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.CTO_ENDORSER_GRP</code>.
     */
    public final TableField<CtmsCtFormRecord, String> CTO_ENDORSER_GRP = createField("CTO_ENDORSER_GRP", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.TRANSACTION_TYPE</code>.
     */
    public final TableField<CtmsCtFormRecord, String> TRANSACTION_TYPE = createField("TRANSACTION_TYPE", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.HAS_AGMT</code>.
     */
    public final TableField<CtmsCtFormRecord, Byte> HAS_AGMT = createField("HAS_AGMT", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_NAME</code>.
     */
    public final TableField<CtmsCtFormRecord, String> AGMT_NAME = createField("AGMT_NAME", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_SIGN_DATE</code>.
     */
    public final TableField<CtmsCtFormRecord, Date> AGMT_SIGN_DATE = createField("AGMT_SIGN_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_DURATION_TYPE</code>.
     */
    public final TableField<CtmsCtFormRecord, String> AGMT_DURATION_TYPE = createField("AGMT_DURATION_TYPE", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_START_DATE</code>.
     */
    public final TableField<CtmsCtFormRecord, Date> AGMT_START_DATE = createField("AGMT_START_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_END_DATE</code>.
     */
    public final TableField<CtmsCtFormRecord, Date> AGMT_END_DATE = createField("AGMT_END_DATE", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW_UNIT</code>.
     */
    public final TableField<CtmsCtFormRecord, String> AGMT_AUTO_RENEW_UNIT = createField("AGMT_AUTO_RENEW_UNIT", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW</code>.
     */
    public final TableField<CtmsCtFormRecord, BigDecimal> AGMT_AUTO_RENEW = createField("AGMT_AUTO_RENEW", org.jooq.impl.SQLDataType.DECIMAL(20, 2), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.PRICING_TERM</code>.
     */
    public final TableField<CtmsCtFormRecord, String> PRICING_TERM = createField("PRICING_TERM", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.PRICING_BASIS</code>.
     */
    public final TableField<CtmsCtFormRecord, String> PRICING_BASIS = createField("PRICING_BASIS", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_PAYMENT</code>.
     */
    public final TableField<CtmsCtFormRecord, BigDecimal> PROJECTED_ANNUAL_PAYMENT = createField("PROJECTED_ANNUAL_PAYMENT", org.jooq.impl.SQLDataType.DECIMAL(38, 5), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_RECEIVE</code>.
     */
    public final TableField<CtmsCtFormRecord, BigDecimal> PROJECTED_ANNUAL_RECEIVE = createField("PROJECTED_ANNUAL_RECEIVE", org.jooq.impl.SQLDataType.DECIMAL(38, 5), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AP</code>.
     */
    public final TableField<CtmsCtFormRecord, Byte> IS_UNKNOWN_SMALL_AP = createField("IS_UNKNOWN_SMALL_AP", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AR</code>.
     */
    public final TableField<CtmsCtFormRecord, Byte> IS_UNKNOWN_SMALL_AR = createField("IS_UNKNOWN_SMALL_AR", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.STATUS</code>.
     */
    public final TableField<CtmsCtFormRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.IS_ARCHIVED</code>.
     */
    public final TableField<CtmsCtFormRecord, Byte> IS_ARCHIVED = createField("IS_ARCHIVED", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.REPORTED_BY</code>.
     */
    public final TableField<CtmsCtFormRecord, String> REPORTED_BY = createField("REPORTED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.REPORTED_AT</code>.
     */
    public final TableField<CtmsCtFormRecord, Timestamp> REPORTED_AT = createField("REPORTED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.REMARKS</code>.
     */
    public final TableField<CtmsCtFormRecord, String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.CTO_REMARKS</code>.
     */
    public final TableField<CtmsCtFormRecord, String> CTO_REMARKS = createField("CTO_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_BY</code>.
     */
    public final TableField<CtmsCtFormRecord, String> CTO_REVIEWED_BY = createField("CTO_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_AT</code>.
     */
    public final TableField<CtmsCtFormRecord, Timestamp> CTO_REVIEWED_AT = createField("CTO_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.LSD_REMARKS</code>.
     */
    public final TableField<CtmsCtFormRecord, String> LSD_REMARKS = createField("LSD_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_BY</code>.
     */
    public final TableField<CtmsCtFormRecord, String> LSD_REVIEWED_BY = createField("LSD_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_AT</code>.
     */
    public final TableField<CtmsCtFormRecord, Timestamp> LSD_REVIEWED_AT = createField("LSD_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.CREATED_AT</code>.
     */
    public final TableField<CtmsCtFormRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.UPDATED_BY</code>.
     */
    public final TableField<CtmsCtFormRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM.UPDATED_AT</code>.
     */
    public final TableField<CtmsCtFormRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_CT_FORM</code> table reference
     */
    public CtmsCtForm() {
        this(DSL.name("CTMS_CT_FORM"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM</code> table reference
     */
    public CtmsCtForm(String alias) {
        this(DSL.name(alias), CTMS_CT_FORM);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM</code> table reference
     */
    public CtmsCtForm(Name alias) {
        this(alias, CTMS_CT_FORM);
    }

    private CtmsCtForm(Name alias, Table<CtmsCtFormRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCtForm(Name alias, Table<CtmsCtFormRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_64);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCtFormRecord> getPrimaryKey() {
        return Keys.CTMS_CT_FORM_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCtFormRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCtFormRecord>>asList(Keys.CTMS_CT_FORM_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtForm as(String alias) {
        return new CtmsCtForm(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtForm as(Name alias) {
        return new CtmsCtForm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtForm rename(String name) {
        return new CtmsCtForm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtForm rename(Name name) {
        return new CtmsCtForm(name, null);
    }
}
