/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyGrpRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyGrp extends TableImpl<CtmsCompanyGrpRecord> {

    private static final long serialVersionUID = 446777136;

    /**
     * The reference instance of <code>PUBLIC.CTMS_COMPANY_GRP</code>
     */
    public static final CtmsCompanyGrp CTMS_COMPANY_GRP = new CtmsCompanyGrp();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCompanyGrpRecord> getRecordType() {
        return CtmsCompanyGrpRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_GRP.ID</code>.
     */
    public final TableField<CtmsCompanyGrpRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_GRP.CODE</code>.
     */
    public final TableField<CtmsCompanyGrpRecord, String> CODE = createField("CODE", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_COMPANY_GRP.NAME</code>.
     */
    public final TableField<CtmsCompanyGrpRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>PUBLIC.CTMS_COMPANY_GRP</code> table reference
     */
    public CtmsCompanyGrp() {
        this(DSL.name("CTMS_COMPANY_GRP"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_GRP</code> table reference
     */
    public CtmsCompanyGrp(String alias) {
        this(DSL.name(alias), CTMS_COMPANY_GRP);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_COMPANY_GRP</code> table reference
     */
    public CtmsCompanyGrp(Name alias) {
        this(alias, CTMS_COMPANY_GRP);
    }

    private CtmsCompanyGrp(Name alias, Table<CtmsCompanyGrpRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCompanyGrp(Name alias, Table<CtmsCompanyGrpRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CTMS_COMPANY_GRP_U01_INDEX_6, Indexes.PRIMARY_KEY_6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCompanyGrpRecord> getPrimaryKey() {
        return Keys.CTMS_COMPANY_GRP_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCompanyGrpRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCompanyGrpRecord>>asList(Keys.CTMS_COMPANY_GRP_PK, Keys.CTMS_COMPANY_GRP_U01);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyGrp as(String alias) {
        return new CtmsCompanyGrp(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyGrp as(Name alias) {
        return new CtmsCompanyGrp(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyGrp rename(String name) {
        return new CtmsCompanyGrp(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCompanyGrp rename(Name name) {
        return new CtmsCompanyGrp(name, null);
    }
}
