/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsAuditChecklistRecord;

import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsAuditChecklist extends TableImpl<CtmsAuditChecklistRecord> {

    private static final long serialVersionUID = 2145322630;

    /**
     * The reference instance of <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code>
     */
    public static final CtmsAuditChecklist CTMS_AUDIT_CHECKLIST = new CtmsAuditChecklist();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsAuditChecklistRecord> getRecordType() {
        return CtmsAuditChecklistRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.ID</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV1</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> RPT_USER_GRP_LV1 = createField("RPT_USER_GRP_LV1", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV2</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> RPT_USER_GRP_LV2 = createField("RPT_USER_GRP_LV2", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV3</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> RPT_USER_GRP_LV3 = createField("RPT_USER_GRP_LV3", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_ENDORSER_GRP</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> CTO_ENDORSER_GRP = createField("CTO_ENDORSER_GRP", org.jooq.impl.SQLDataType.VARCHAR(300), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.PERIOD</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> PERIOD = createField("PERIOD", org.jooq.impl.SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_CHANGES</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Byte> HAS_CHANGES = createField("HAS_CHANGES", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_UNREPORTED</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Byte> HAS_UNREPORTED = createField("HAS_UNREPORTED", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.IS_AWARE_POTENTIAL</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Byte> IS_AWARE_POTENTIAL = createField("IS_AWARE_POTENTIAL", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.STATUS</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_BY</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> REPORTED_BY = createField("REPORTED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_AT</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Timestamp> REPORTED_AT = createField("REPORTED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REMARKS</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> REMARKS = createField("REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REMARKS</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> CTO_REMARKS = createField("CTO_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_BY</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> CTO_REVIEWED_BY = createField("CTO_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_AT</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Timestamp> CTO_REVIEWED_AT = createField("CTO_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REMARKS</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> LSD_REMARKS = createField("LSD_REMARKS", org.jooq.impl.SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_BY</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> LSD_REVIEWED_BY = createField("LSD_REVIEWED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_AT</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Timestamp> LSD_REVIEWED_AT = createField("LSD_REVIEWED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_BY</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_AT</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Timestamp> UPDATED_AT = createField("UPDATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CREATED_AT</code>.
     */
    public final TableField<CtmsAuditChecklistRecord, Timestamp> CREATED_AT = createField("CREATED_AT", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code> table reference
     */
    public CtmsAuditChecklist() {
        this(DSL.name("CTMS_AUDIT_CHECKLIST"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code> table reference
     */
    public CtmsAuditChecklist(String alias) {
        this(DSL.name(alias), CTMS_AUDIT_CHECKLIST);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code> table reference
     */
    public CtmsAuditChecklist(Name alias) {
        this(alias, CTMS_AUDIT_CHECKLIST);
    }

    private CtmsAuditChecklist(Name alias, Table<CtmsAuditChecklistRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsAuditChecklist(Name alias, Table<CtmsAuditChecklistRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_B);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsAuditChecklistRecord> getPrimaryKey() {
        return Keys.CTMS_AUDIT_CHECKLIST_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsAuditChecklistRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsAuditChecklistRecord>>asList(Keys.CTMS_AUDIT_CHECKLIST_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklist as(String alias) {
        return new CtmsAuditChecklist(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklist as(Name alias) {
        return new CtmsAuditChecklist(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsAuditChecklist rename(String name) {
        return new CtmsAuditChecklist(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsAuditChecklist rename(Name name) {
        return new CtmsAuditChecklist(name, null);
    }
}
