/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables;


import com.test.springboot.jooq.data.jooq.Indexes;
import com.test.springboot.jooq.data.jooq.Keys;
import com.test.springboot.jooq.data.jooq.Public;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormPtyRecord;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormPty extends TableImpl<CtmsCtFormPtyRecord> {

    private static final long serialVersionUID = -1765938220;

    /**
     * The reference instance of <code>PUBLIC.CTMS_CT_FORM_PTY</code>
     */
    public static final CtmsCtFormPty CTMS_CT_FORM_PTY = new CtmsCtFormPty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CtmsCtFormPtyRecord> getRecordType() {
        return CtmsCtFormPtyRecord.class;
    }

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.ID</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, BigInteger> ID = createField("ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.CT_FORM_ID</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, BigInteger> CT_FORM_ID = createField("CT_FORM_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_ID</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, BigInteger> COMPANY_ID = createField("COMPANY_ID", org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(20), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_CODE</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, String> COMPANY_CODE = createField("COMPANY_CODE", org.jooq.impl.SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_GRP_CODE</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, String> COMPANY_GRP_CODE = createField("COMPANY_GRP_CODE", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.ENGLISH_NAME</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, String> ENGLISH_NAME = createField("ENGLISH_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>PUBLIC.CTMS_CT_FORM_PTY.CHINESE_NAME</code>.
     */
    public final TableField<CtmsCtFormPtyRecord, String> CHINESE_NAME = createField("CHINESE_NAME", org.jooq.impl.SQLDataType.VARCHAR(1000), this, "");

    /**
     * Create a <code>PUBLIC.CTMS_CT_FORM_PTY</code> table reference
     */
    public CtmsCtFormPty() {
        this(DSL.name("CTMS_CT_FORM_PTY"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM_PTY</code> table reference
     */
    public CtmsCtFormPty(String alias) {
        this(DSL.name(alias), CTMS_CT_FORM_PTY);
    }

    /**
     * Create an aliased <code>PUBLIC.CTMS_CT_FORM_PTY</code> table reference
     */
    public CtmsCtFormPty(Name alias) {
        this(alias, CTMS_CT_FORM_PTY);
    }

    private CtmsCtFormPty(Name alias, Table<CtmsCtFormPtyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CtmsCtFormPty(Name alias, Table<CtmsCtFormPtyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CTMS_CT_FORM_PTY_U01_INDEX_1, Indexes.PRIMARY_KEY_14);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CtmsCtFormPtyRecord> getPrimaryKey() {
        return Keys.CTMS_CT_FORM_PTY_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CtmsCtFormPtyRecord>> getKeys() {
        return Arrays.<UniqueKey<CtmsCtFormPtyRecord>>asList(Keys.CTMS_CT_FORM_PTY_PK, Keys.CTMS_CT_FORM_PTY_U01);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPty as(String alias) {
        return new CtmsCtFormPty(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPty as(Name alias) {
        return new CtmsCtFormPty(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtFormPty rename(String name) {
        return new CtmsCtFormPty(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CtmsCtFormPty rename(Name name) {
        return new CtmsCtFormPty(name, null);
    }
}
