/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq;


import com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompany;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtForm;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService;
import com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier;
import com.test.springboot.jooq.data.jooq.tables.CtmsUser;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference;
import com.test.springboot.jooq.data.jooq.tables.TestUser;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsAuditChecklistRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyCatRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyGrpRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyHolderRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyNameRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCompanyRequestRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormAgmtFilesRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormOtherPtyRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormPtyRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsCtFormServiceRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsReportGrpHierRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserGroupRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserPreferenceRecord;
import com.test.springboot.jooq.data.jooq.tables.records.CtmsUserRecord;
import com.test.springboot.jooq.data.jooq.tables.records.TestUserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CtmsAuditChecklistRecord> CTMS_AUDIT_CHECKLIST_PK = UniqueKeys0.CTMS_AUDIT_CHECKLIST_PK;
    public static final UniqueKey<CtmsCompanyRecord> CTMS_COMPANY_PK = UniqueKeys0.CTMS_COMPANY_PK;
    public static final UniqueKey<CtmsCompanyRecord> CTMS_COMPANY_U01 = UniqueKeys0.CTMS_COMPANY_U01;
    public static final UniqueKey<CtmsCompanyCatRecord> CTMS_COMPANY_CAT_PK = UniqueKeys0.CTMS_COMPANY_CAT_PK;
    public static final UniqueKey<CtmsCompanyCatRecord> CTMS_COMPANY_CAT_U01 = UniqueKeys0.CTMS_COMPANY_CAT_U01;
    public static final UniqueKey<CtmsCompanyGrpRecord> CTMS_COMPANY_GRP_PK = UniqueKeys0.CTMS_COMPANY_GRP_PK;
    public static final UniqueKey<CtmsCompanyGrpRecord> CTMS_COMPANY_GRP_U01 = UniqueKeys0.CTMS_COMPANY_GRP_U01;
    public static final UniqueKey<CtmsCompanyHolderRecord> CTMS_COMPANY_HOLDER_PK = UniqueKeys0.CTMS_COMPANY_HOLDER_PK;
    public static final UniqueKey<CtmsCompanyNameRecord> CTMS_COMPANY_NAME_PK = UniqueKeys0.CTMS_COMPANY_NAME_PK;
    public static final UniqueKey<CtmsCompanyRequestRecord> CTMS_COMPANY_REQUEST_PK = UniqueKeys0.CTMS_COMPANY_REQUEST_PK;
    public static final UniqueKey<CtmsCtFormRecord> CTMS_CT_FORM_PK = UniqueKeys0.CTMS_CT_FORM_PK;
    public static final UniqueKey<CtmsCtFormAgmtFilesRecord> CTMS_CT_FORM_AGMT_FILES_PK = UniqueKeys0.CTMS_CT_FORM_AGMT_FILES_PK;
    public static final UniqueKey<CtmsCtFormOtherPtyRecord> CTMS_CT_FORM_OTHER_PTY_PK = UniqueKeys0.CTMS_CT_FORM_OTHER_PTY_PK;
    public static final UniqueKey<CtmsCtFormOtherPtyRecord> CTMS_CT_FORM_OTHER_PTY_U01 = UniqueKeys0.CTMS_CT_FORM_OTHER_PTY_U01;
    public static final UniqueKey<CtmsCtFormPtyRecord> CTMS_CT_FORM_PTY_PK = UniqueKeys0.CTMS_CT_FORM_PTY_PK;
    public static final UniqueKey<CtmsCtFormPtyRecord> CTMS_CT_FORM_PTY_U01 = UniqueKeys0.CTMS_CT_FORM_PTY_U01;
    public static final UniqueKey<CtmsCtFormServiceRecord> CTMS_CT_FORM_SERVICE_PK = UniqueKeys0.CTMS_CT_FORM_SERVICE_PK;
    public static final UniqueKey<CtmsCtFormServiceRecord> CTMS_CT_FORM_SERVICE_U01 = UniqueKeys0.CTMS_CT_FORM_SERVICE_U01;
    public static final UniqueKey<CtmsReportGrpHierRecord> CTMS_REPORT_GRP_HIER_PK = UniqueKeys0.CTMS_REPORT_GRP_HIER_PK;
    public static final UniqueKey<CtmsReportGrpHierRecord> CTMS_REPORT_GRP_HIER_U01 = UniqueKeys0.CTMS_REPORT_GRP_HIER_U01;
    public static final UniqueKey<CtmsUserRecord> CTMS_USERS_PK = UniqueKeys0.CTMS_USERS_PK;
    public static final UniqueKey<CtmsUserRecord> CTMS_USERS_U01 = UniqueKeys0.CTMS_USERS_U01;
    public static final UniqueKey<CtmsUserGroupRecord> CTMS_USER_GROUP_PK = UniqueKeys0.CTMS_USER_GROUP_PK;
    public static final UniqueKey<CtmsUserPreferenceRecord> CTMS_USERS_PERFERENCE_PK = UniqueKeys0.CTMS_USERS_PERFERENCE_PK;
    public static final UniqueKey<TestUserRecord> TEST_USERS_PK = UniqueKeys0.TEST_USERS_PK;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CtmsAuditChecklistRecord> CTMS_AUDIT_CHECKLIST_PK = Internal.createUniqueKey(CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST, "CTMS_AUDIT_CHECKLIST_PK", CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.ID);
        public static final UniqueKey<CtmsCompanyRecord> CTMS_COMPANY_PK = Internal.createUniqueKey(CtmsCompany.CTMS_COMPANY, "CTMS_COMPANY_PK", CtmsCompany.CTMS_COMPANY.ID);
        public static final UniqueKey<CtmsCompanyRecord> CTMS_COMPANY_U01 = Internal.createUniqueKey(CtmsCompany.CTMS_COMPANY, "CTMS_COMPANY_U01", CtmsCompany.CTMS_COMPANY.CODE);
        public static final UniqueKey<CtmsCompanyCatRecord> CTMS_COMPANY_CAT_PK = Internal.createUniqueKey(CtmsCompanyCat.CTMS_COMPANY_CAT, "CTMS_COMPANY_CAT_PK", CtmsCompanyCat.CTMS_COMPANY_CAT.ID);
        public static final UniqueKey<CtmsCompanyCatRecord> CTMS_COMPANY_CAT_U01 = Internal.createUniqueKey(CtmsCompanyCat.CTMS_COMPANY_CAT, "CTMS_COMPANY_CAT_U01", CtmsCompanyCat.CTMS_COMPANY_CAT.CODE);
        public static final UniqueKey<CtmsCompanyGrpRecord> CTMS_COMPANY_GRP_PK = Internal.createUniqueKey(CtmsCompanyGrp.CTMS_COMPANY_GRP, "CTMS_COMPANY_GRP_PK", CtmsCompanyGrp.CTMS_COMPANY_GRP.ID);
        public static final UniqueKey<CtmsCompanyGrpRecord> CTMS_COMPANY_GRP_U01 = Internal.createUniqueKey(CtmsCompanyGrp.CTMS_COMPANY_GRP, "CTMS_COMPANY_GRP_U01", CtmsCompanyGrp.CTMS_COMPANY_GRP.CODE);
        public static final UniqueKey<CtmsCompanyHolderRecord> CTMS_COMPANY_HOLDER_PK = Internal.createUniqueKey(CtmsCompanyHolder.CTMS_COMPANY_HOLDER, "CTMS_COMPANY_HOLDER_PK", CtmsCompanyHolder.CTMS_COMPANY_HOLDER.ID);
        public static final UniqueKey<CtmsCompanyNameRecord> CTMS_COMPANY_NAME_PK = Internal.createUniqueKey(CtmsCompanyName.CTMS_COMPANY_NAME, "CTMS_COMPANY_NAME_PK", CtmsCompanyName.CTMS_COMPANY_NAME.ID);
        public static final UniqueKey<CtmsCompanyRequestRecord> CTMS_COMPANY_REQUEST_PK = Internal.createUniqueKey(CtmsCompanyRequest.CTMS_COMPANY_REQUEST, "CTMS_COMPANY_REQUEST_PK", CtmsCompanyRequest.CTMS_COMPANY_REQUEST.ID);
        public static final UniqueKey<CtmsCtFormRecord> CTMS_CT_FORM_PK = Internal.createUniqueKey(CtmsCtForm.CTMS_CT_FORM, "CTMS_CT_FORM_PK", CtmsCtForm.CTMS_CT_FORM.ID);
        public static final UniqueKey<CtmsCtFormAgmtFilesRecord> CTMS_CT_FORM_AGMT_FILES_PK = Internal.createUniqueKey(CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES, "CTMS_CT_FORM_AGMT_FILES_PK", CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.CT_FORM_ID, CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.ID);
        public static final UniqueKey<CtmsCtFormOtherPtyRecord> CTMS_CT_FORM_OTHER_PTY_PK = Internal.createUniqueKey(CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY, "CTMS_CT_FORM_OTHER_PTY_PK", CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.ID);
        public static final UniqueKey<CtmsCtFormOtherPtyRecord> CTMS_CT_FORM_OTHER_PTY_U01 = Internal.createUniqueKey(CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY, "CTMS_CT_FORM_OTHER_PTY_U01", CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.CT_FORM_ID, CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.COMPANY_NAME);
        public static final UniqueKey<CtmsCtFormPtyRecord> CTMS_CT_FORM_PTY_PK = Internal.createUniqueKey(CtmsCtFormPty.CTMS_CT_FORM_PTY, "CTMS_CT_FORM_PTY_PK", CtmsCtFormPty.CTMS_CT_FORM_PTY.ID);
        public static final UniqueKey<CtmsCtFormPtyRecord> CTMS_CT_FORM_PTY_U01 = Internal.createUniqueKey(CtmsCtFormPty.CTMS_CT_FORM_PTY, "CTMS_CT_FORM_PTY_U01", CtmsCtFormPty.CTMS_CT_FORM_PTY.CT_FORM_ID, CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_ID);
        public static final UniqueKey<CtmsCtFormServiceRecord> CTMS_CT_FORM_SERVICE_PK = Internal.createUniqueKey(CtmsCtFormService.CTMS_CT_FORM_SERVICE, "CTMS_CT_FORM_SERVICE_PK", CtmsCtFormService.CTMS_CT_FORM_SERVICE.ID);
        public static final UniqueKey<CtmsCtFormServiceRecord> CTMS_CT_FORM_SERVICE_U01 = Internal.createUniqueKey(CtmsCtFormService.CTMS_CT_FORM_SERVICE, "CTMS_CT_FORM_SERVICE_U01", CtmsCtFormService.CTMS_CT_FORM_SERVICE.CT_FORM_ID, CtmsCtFormService.CTMS_CT_FORM_SERVICE.TYPE_CODE);
        public static final UniqueKey<CtmsReportGrpHierRecord> CTMS_REPORT_GRP_HIER_PK = Internal.createUniqueKey(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER, "CTMS_REPORT_GRP_HIER_PK", CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.ID);
        public static final UniqueKey<CtmsReportGrpHierRecord> CTMS_REPORT_GRP_HIER_U01 = Internal.createUniqueKey(CtmsReportGrpHier.CTMS_REPORT_GRP_HIER, "CTMS_REPORT_GRP_HIER_U01", CtmsReportGrpHier.CTMS_REPORT_GRP_HIER.CODE);
        public static final UniqueKey<CtmsUserRecord> CTMS_USERS_PK = Internal.createUniqueKey(CtmsUser.CTMS_USER, "CTMS_USERS_PK", CtmsUser.CTMS_USER.ID);
        public static final UniqueKey<CtmsUserRecord> CTMS_USERS_U01 = Internal.createUniqueKey(CtmsUser.CTMS_USER, "CTMS_USERS_U01", CtmsUser.CTMS_USER.LOGIN_ID);
        public static final UniqueKey<CtmsUserGroupRecord> CTMS_USER_GROUP_PK = Internal.createUniqueKey(CtmsUserGroup.CTMS_USER_GROUP, "CTMS_USER_GROUP_PK", CtmsUserGroup.CTMS_USER_GROUP.ID);
        public static final UniqueKey<CtmsUserPreferenceRecord> CTMS_USERS_PERFERENCE_PK = Internal.createUniqueKey(CtmsUserPreference.CTMS_USER_PREFERENCE, "CTMS_USERS_PERFERENCE_PK", CtmsUserPreference.CTMS_USER_PREFERENCE.ID);
        public static final UniqueKey<TestUserRecord> TEST_USERS_PK = Internal.createUniqueKey(TestUser.TEST_USER, "TEST_USERS_PK", TestUser.TEST_USER.ID);
    }
}
