/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq;


import com.test.springboot.jooq.data.jooq.tables.City;
import com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompany;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtForm;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService;
import com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier;
import com.test.springboot.jooq.data.jooq.tables.CtmsUser;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference;
import com.test.springboot.jooq.data.jooq.tables.TestUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1429011260;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.CITY</code>.
     */
    public final City CITY = com.test.springboot.jooq.data.jooq.tables.City.CITY;

    /**
     * The table <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code>.
     */
    public final CtmsAuditChecklist CTMS_AUDIT_CHECKLIST = com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY</code>.
     */
    public final CtmsCompany CTMS_COMPANY = com.test.springboot.jooq.data.jooq.tables.CtmsCompany.CTMS_COMPANY;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_CAT</code>.
     */
    public final CtmsCompanyCat CTMS_COMPANY_CAT = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat.CTMS_COMPANY_CAT;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_GRP</code>.
     */
    public final CtmsCompanyGrp CTMS_COMPANY_GRP = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp.CTMS_COMPANY_GRP;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_HOLDER</code>.
     */
    public final CtmsCompanyHolder CTMS_COMPANY_HOLDER = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder.CTMS_COMPANY_HOLDER;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_NAME</code>.
     */
    public final CtmsCompanyName CTMS_COMPANY_NAME = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName.CTMS_COMPANY_NAME;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_REQUEST</code>.
     */
    public final CtmsCompanyRequest CTMS_COMPANY_REQUEST = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest.CTMS_COMPANY_REQUEST;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM</code>.
     */
    public final CtmsCtForm CTMS_CT_FORM = com.test.springboot.jooq.data.jooq.tables.CtmsCtForm.CTMS_CT_FORM;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES</code>.
     */
    public final CtmsCtFormAgmtFiles CTMS_CT_FORM_AGMT_FILES = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY</code>.
     */
    public final CtmsCtFormOtherPty CTMS_CT_FORM_OTHER_PTY = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_PTY</code>.
     */
    public final CtmsCtFormPty CTMS_CT_FORM_PTY = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty.CTMS_CT_FORM_PTY;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_SERVICE</code>.
     */
    public final CtmsCtFormService CTMS_CT_FORM_SERVICE = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService.CTMS_CT_FORM_SERVICE;

    /**
     * The table <code>PUBLIC.CTMS_REPORT_GRP_HIER</code>.
     */
    public final CtmsReportGrpHier CTMS_REPORT_GRP_HIER = com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier.CTMS_REPORT_GRP_HIER;

    /**
     * The table <code>PUBLIC.CTMS_USER</code>.
     */
    public final CtmsUser CTMS_USER = com.test.springboot.jooq.data.jooq.tables.CtmsUser.CTMS_USER;

    /**
     * The table <code>PUBLIC.CTMS_USER_GROUP</code>.
     */
    public final CtmsUserGroup CTMS_USER_GROUP = com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup.CTMS_USER_GROUP;

    /**
     * The table <code>PUBLIC.CTMS_USER_PREFERENCE</code>.
     */
    public final CtmsUserPreference CTMS_USER_PREFERENCE = com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference.CTMS_USER_PREFERENCE;

    /**
     * The table <code>PUBLIC.TEST_USER</code>.
     */
    public final TestUser TEST_USER = com.test.springboot.jooq.data.jooq.tables.TestUser.TEST_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.CTMS_AUDIT_CHECKLIST_ID_SEQ,
            Sequences.CTMS_COMPANY_CAT_ID_SEQ,
            Sequences.CTMS_COMPANY_GRP_ID_SEQ,
            Sequences.CTMS_COMPANY_HOLDER_ID_SEQ,
            Sequences.CTMS_COMPANY_ID_SEQ,
            Sequences.CTMS_COMPANY_NAME_ID_SEQ,
            Sequences.CTMS_COMPANY_REQUEST_ID_SEQ,
            Sequences.CTMS_CT_FORM_AGMT_FILES_ID_SEQ,
            Sequences.CTMS_CT_FORM_ID_SEQ,
            Sequences.CTMS_CT_FORM_OTHER_PTY_ID_SEQ,
            Sequences.CTMS_CT_FORM_PTY_ID_SEQ,
            Sequences.CTMS_CT_FORM_SERVICE_ID_SEQ,
            Sequences.CTMS_USER_GROUP_ID_SEQ,
            Sequences.CTMS_USER_ID_SEQ,
            Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            City.CITY,
            CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST,
            CtmsCompany.CTMS_COMPANY,
            CtmsCompanyCat.CTMS_COMPANY_CAT,
            CtmsCompanyGrp.CTMS_COMPANY_GRP,
            CtmsCompanyHolder.CTMS_COMPANY_HOLDER,
            CtmsCompanyName.CTMS_COMPANY_NAME,
            CtmsCompanyRequest.CTMS_COMPANY_REQUEST,
            CtmsCtForm.CTMS_CT_FORM,
            CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES,
            CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY,
            CtmsCtFormPty.CTMS_CT_FORM_PTY,
            CtmsCtFormService.CTMS_CT_FORM_SERVICE,
            CtmsReportGrpHier.CTMS_REPORT_GRP_HIER,
            CtmsUser.CTMS_USER,
            CtmsUserGroup.CTMS_USER_GROUP,
            CtmsUserPreference.CTMS_USER_PREFERENCE,
            TestUser.TEST_USER);
    }
}
