/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq;


import com.test.springboot.jooq.data.jooq.tables.City;
import com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompany;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName;
import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtForm;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty;
import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService;
import com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier;
import com.test.springboot.jooq.data.jooq.tables.CtmsUser;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup;
import com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference;
import com.test.springboot.jooq.data.jooq.tables.TestUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CITY</code>.
     */
    public static final City CITY = com.test.springboot.jooq.data.jooq.tables.City.CITY;

    /**
     * The table <code>PUBLIC.CTMS_AUDIT_CHECKLIST</code>.
     */
    public static final CtmsAuditChecklist CTMS_AUDIT_CHECKLIST = com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY</code>.
     */
    public static final CtmsCompany CTMS_COMPANY = com.test.springboot.jooq.data.jooq.tables.CtmsCompany.CTMS_COMPANY;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_CAT</code>.
     */
    public static final CtmsCompanyCat CTMS_COMPANY_CAT = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyCat.CTMS_COMPANY_CAT;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_GRP</code>.
     */
    public static final CtmsCompanyGrp CTMS_COMPANY_GRP = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyGrp.CTMS_COMPANY_GRP;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_HOLDER</code>.
     */
    public static final CtmsCompanyHolder CTMS_COMPANY_HOLDER = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder.CTMS_COMPANY_HOLDER;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_NAME</code>.
     */
    public static final CtmsCompanyName CTMS_COMPANY_NAME = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyName.CTMS_COMPANY_NAME;

    /**
     * The table <code>PUBLIC.CTMS_COMPANY_REQUEST</code>.
     */
    public static final CtmsCompanyRequest CTMS_COMPANY_REQUEST = com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest.CTMS_COMPANY_REQUEST;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM</code>.
     */
    public static final CtmsCtForm CTMS_CT_FORM = com.test.springboot.jooq.data.jooq.tables.CtmsCtForm.CTMS_CT_FORM;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES</code>.
     */
    public static final CtmsCtFormAgmtFiles CTMS_CT_FORM_AGMT_FILES = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY</code>.
     */
    public static final CtmsCtFormOtherPty CTMS_CT_FORM_OTHER_PTY = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_PTY</code>.
     */
    public static final CtmsCtFormPty CTMS_CT_FORM_PTY = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty.CTMS_CT_FORM_PTY;

    /**
     * The table <code>PUBLIC.CTMS_CT_FORM_SERVICE</code>.
     */
    public static final CtmsCtFormService CTMS_CT_FORM_SERVICE = com.test.springboot.jooq.data.jooq.tables.CtmsCtFormService.CTMS_CT_FORM_SERVICE;

    /**
     * The table <code>PUBLIC.CTMS_REPORT_GRP_HIER</code>.
     */
    public static final CtmsReportGrpHier CTMS_REPORT_GRP_HIER = com.test.springboot.jooq.data.jooq.tables.CtmsReportGrpHier.CTMS_REPORT_GRP_HIER;

    /**
     * The table <code>PUBLIC.CTMS_USER</code>.
     */
    public static final CtmsUser CTMS_USER = com.test.springboot.jooq.data.jooq.tables.CtmsUser.CTMS_USER;

    /**
     * The table <code>PUBLIC.CTMS_USER_GROUP</code>.
     */
    public static final CtmsUserGroup CTMS_USER_GROUP = com.test.springboot.jooq.data.jooq.tables.CtmsUserGroup.CTMS_USER_GROUP;

    /**
     * The table <code>PUBLIC.CTMS_USER_PREFERENCE</code>.
     */
    public static final CtmsUserPreference CTMS_USER_PREFERENCE = com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference.CTMS_USER_PREFERENCE;

    /**
     * The table <code>PUBLIC.TEST_USER</code>.
     */
    public static final TestUser TEST_USER = com.test.springboot.jooq.data.jooq.tables.TestUser.TEST_USER;
}
