/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsUserPreference;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsUserPreferenceRecord extends UpdatableRecordImpl<CtmsUserPreferenceRecord> implements Record6<BigInteger, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 2003765755;

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV1</code>.
     */
    public void setDefaultRptUserGrpLv1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV1</code>.
     */
    public String getDefaultRptUserGrpLv1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV2</code>.
     */
    public void setDefaultRptUserGrpLv2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV2</code>.
     */
    public String getDefaultRptUserGrpLv2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV3</code>.
     */
    public void setDefaultRptUserGrpLv3(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV3</code>.
     */
    public String getDefaultRptUserGrpLv3() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_USER_PREFERENCE.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<BigInteger, String, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<BigInteger, String, String, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.DEFAULT_RPT_USER_GRP_LV3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return CtmsUserPreference.CTMS_USER_PREFERENCE.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getDefaultRptUserGrpLv1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDefaultRptUserGrpLv2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDefaultRptUserGrpLv3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDefaultRptUserGrpLv1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDefaultRptUserGrpLv2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDefaultRptUserGrpLv3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value2(String value) {
        setDefaultRptUserGrpLv1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value3(String value) {
        setDefaultRptUserGrpLv2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value4(String value) {
        setDefaultRptUserGrpLv3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value5(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsUserPreferenceRecord values(BigInteger value1, String value2, String value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsUserPreferenceRecord
     */
    public CtmsUserPreferenceRecord() {
        super(CtmsUserPreference.CTMS_USER_PREFERENCE);
    }

    /**
     * Create a detached, initialised CtmsUserPreferenceRecord
     */
    public CtmsUserPreferenceRecord(BigInteger id, String defaultRptUserGrpLv1, String defaultRptUserGrpLv2, String defaultRptUserGrpLv3, String updatedBy, Timestamp updatedAt) {
        super(CtmsUserPreference.CTMS_USER_PREFERENCE);

        set(0, id);
        set(1, defaultRptUserGrpLv1);
        set(2, defaultRptUserGrpLv2);
        set(3, defaultRptUserGrpLv3);
        set(4, updatedBy);
        set(5, updatedAt);
    }
}
