/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsAuditChecklist;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsAuditChecklistRecord extends UpdatableRecordImpl<CtmsAuditChecklistRecord> implements Record22<BigInteger, String, String, String, String, String, Byte, Byte, Byte, String, String, Timestamp, String, String, String, Timestamp, String, String, Timestamp, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -467320103;

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV1</code>.
     */
    public void setRptUserGrpLv1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV1</code>.
     */
    public String getRptUserGrpLv1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV2</code>.
     */
    public void setRptUserGrpLv2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV2</code>.
     */
    public String getRptUserGrpLv2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV3</code>.
     */
    public void setRptUserGrpLv3(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV3</code>.
     */
    public String getRptUserGrpLv3() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_ENDORSER_GRP</code>.
     */
    public void setCtoEndorserGrp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_ENDORSER_GRP</code>.
     */
    public String getCtoEndorserGrp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.PERIOD</code>.
     */
    public void setPeriod(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.PERIOD</code>.
     */
    public String getPeriod() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_CHANGES</code>.
     */
    public void setHasChanges(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_CHANGES</code>.
     */
    public Byte getHasChanges() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_UNREPORTED</code>.
     */
    public void setHasUnreported(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.HAS_UNREPORTED</code>.
     */
    public Byte getHasUnreported() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.IS_AWARE_POTENTIAL</code>.
     */
    public void setIsAwarePotential(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.IS_AWARE_POTENTIAL</code>.
     */
    public Byte getIsAwarePotential() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.STATUS</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_BY</code>.
     */
    public void setReportedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_BY</code>.
     */
    public String getReportedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_AT</code>.
     */
    public void setReportedAt(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REPORTED_AT</code>.
     */
    public Timestamp getReportedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REMARKS</code>.
     */
    public void setCtoRemarks(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REMARKS</code>.
     */
    public String getCtoRemarks() {
        return (String) get(13);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_BY</code>.
     */
    public void setCtoReviewedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_BY</code>.
     */
    public String getCtoReviewedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_AT</code>.
     */
    public void setCtoReviewedAt(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_AT</code>.
     */
    public Timestamp getCtoReviewedAt() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REMARKS</code>.
     */
    public void setLsdRemarks(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REMARKS</code>.
     */
    public String getLsdRemarks() {
        return (String) get(16);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_BY</code>.
     */
    public void setLsdReviewedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_BY</code>.
     */
    public String getLsdReviewedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_AT</code>.
     */
    public void setLsdReviewedAt(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_AT</code>.
     */
    public Timestamp getLsdReviewedAt() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(20);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_AUDIT_CHECKLIST.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<BigInteger, String, String, String, String, String, Byte, Byte, Byte, String, String, Timestamp, String, String, String, Timestamp, String, String, Timestamp, String, Timestamp, Timestamp> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<BigInteger, String, String, String, String, String, Byte, Byte, Byte, String, String, Timestamp, String, String, String, Timestamp, String, String, Timestamp, String, Timestamp, Timestamp> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.RPT_USER_GRP_LV3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.CTO_ENDORSER_GRP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.PERIOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.HAS_CHANGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.HAS_UNREPORTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.IS_AWARE_POTENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.REPORTED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.REPORTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.CTO_REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.CTO_REVIEWED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field17() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.LSD_REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.LSD_REVIEWED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field20() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field21() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field22() {
        return CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRptUserGrpLv1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRptUserGrpLv2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRptUserGrpLv3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCtoEndorserGrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getHasChanges();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getHasUnreported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsAwarePotential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getReportedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getReportedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getCtoRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getCtoReviewedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getCtoReviewedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component17() {
        return getLsdRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getLsdReviewedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component19() {
        return getLsdReviewedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component20() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component21() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component22() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRptUserGrpLv1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRptUserGrpLv2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRptUserGrpLv3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCtoEndorserGrp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPeriod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getHasChanges();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getHasUnreported();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsAwarePotential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getReportedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getReportedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCtoRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getCtoReviewedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getCtoReviewedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value17() {
        return getLsdRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getLsdReviewedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getLsdReviewedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value20() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value21() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value22() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value2(String value) {
        setRptUserGrpLv1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value3(String value) {
        setRptUserGrpLv2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value4(String value) {
        setRptUserGrpLv3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value5(String value) {
        setCtoEndorserGrp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value6(String value) {
        setPeriod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value7(Byte value) {
        setHasChanges(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value8(Byte value) {
        setHasUnreported(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value9(Byte value) {
        setIsAwarePotential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value10(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value11(String value) {
        setReportedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value12(Timestamp value) {
        setReportedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value13(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value14(String value) {
        setCtoRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value15(String value) {
        setCtoReviewedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value16(Timestamp value) {
        setCtoReviewedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value17(String value) {
        setLsdRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value18(String value) {
        setLsdReviewedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value19(Timestamp value) {
        setLsdReviewedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value20(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value21(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord value22(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsAuditChecklistRecord values(BigInteger value1, String value2, String value3, String value4, String value5, String value6, Byte value7, Byte value8, Byte value9, String value10, String value11, Timestamp value12, String value13, String value14, String value15, Timestamp value16, String value17, String value18, Timestamp value19, String value20, Timestamp value21, Timestamp value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsAuditChecklistRecord
     */
    public CtmsAuditChecklistRecord() {
        super(CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST);
    }

    /**
     * Create a detached, initialised CtmsAuditChecklistRecord
     */
    public CtmsAuditChecklistRecord(BigInteger id, String rptUserGrpLv1, String rptUserGrpLv2, String rptUserGrpLv3, String ctoEndorserGrp, String period, Byte hasChanges, Byte hasUnreported, Byte isAwarePotential, String status, String reportedBy, Timestamp reportedAt, String remarks, String ctoRemarks, String ctoReviewedBy, Timestamp ctoReviewedAt, String lsdRemarks, String lsdReviewedBy, Timestamp lsdReviewedAt, String updatedBy, Timestamp updatedAt, Timestamp createdAt) {
        super(CtmsAuditChecklist.CTMS_AUDIT_CHECKLIST);

        set(0, id);
        set(1, rptUserGrpLv1);
        set(2, rptUserGrpLv2);
        set(3, rptUserGrpLv3);
        set(4, ctoEndorserGrp);
        set(5, period);
        set(6, hasChanges);
        set(7, hasUnreported);
        set(8, isAwarePotential);
        set(9, status);
        set(10, reportedBy);
        set(11, reportedAt);
        set(12, remarks);
        set(13, ctoRemarks);
        set(14, ctoReviewedBy);
        set(15, ctoReviewedAt);
        set(16, lsdRemarks);
        set(17, lsdReviewedBy);
        set(18, lsdReviewedAt);
        set(19, updatedBy);
        set(20, updatedAt);
        set(21, createdAt);
    }
}
