/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormOtherPty;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormOtherPtyRecord extends UpdatableRecordImpl<CtmsCtFormOtherPtyRecord> implements Record3<BigInteger, BigInteger, String> {

    private static final long serialVersionUID = -1202812414;

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.CT_FORM_ID</code>.
     */
    public void setCtFormId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.CT_FORM_ID</code>.
     */
    public BigInteger getCtFormId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.COMPANY_NAME</code>.
     */
    public void setCompanyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_OTHER_PTY.COMPANY_NAME</code>.
     */
    public String getCompanyName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigInteger, BigInteger, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<BigInteger, BigInteger, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.CT_FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY.COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormOtherPtyRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormOtherPtyRecord value2(BigInteger value) {
        setCtFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormOtherPtyRecord value3(String value) {
        setCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormOtherPtyRecord values(BigInteger value1, BigInteger value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCtFormOtherPtyRecord
     */
    public CtmsCtFormOtherPtyRecord() {
        super(CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY);
    }

    /**
     * Create a detached, initialised CtmsCtFormOtherPtyRecord
     */
    public CtmsCtFormOtherPtyRecord(BigInteger id, BigInteger ctFormId, String companyName) {
        super(CtmsCtFormOtherPty.CTMS_CT_FORM_OTHER_PTY);

        set(0, id);
        set(1, ctFormId);
        set(2, companyName);
    }
}
