/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyRequest;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyRequestRecord extends UpdatableRecordImpl<CtmsCompanyRequestRecord> {

    private static final long serialVersionUID = -1744631850;

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV1</code>.
     */
    public void setRptUserGrpLv1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV1</code>.
     */
    public String getRptUserGrpLv1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV2</code>.
     */
    public void setRptUserGrpLv2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV2</code>.
     */
    public String getRptUserGrpLv2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV3</code>.
     */
    public void setRptUserGrpLv3(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.RPT_USER_GRP_LV3</code>.
     */
    public String getRptUserGrpLv3() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_ENDORSER_GRP</code>.
     */
    public void setCtoEndorserGrp(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_ENDORSER_GRP</code>.
     */
    public String getCtoEndorserGrp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ENGLISH_NAME</code>.
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ENGLISH_NAME</code>.
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CHINESE_NAME</code>.
     */
    public void setChineseName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CHINESE_NAME</code>.
     */
    public String getChineseName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.COMPANY_GRP_ID</code>.
     */
    public void setCompanyGrpId(BigInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.COMPANY_GRP_ID</code>.
     */
    public BigInteger getCompanyGrpId() {
        return (BigInteger) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.BR_NUMBER</code>.
     */
    public void setBrNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.BR_NUMBER</code>.
     */
    public String getBrNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.PHONE_NUMBER</code>.
     */
    public void setPhoneNumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.PHONE_NUMBER</code>.
     */
    public String getPhoneNumber() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.STATUS</code>.
     */
    public void setStatus(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.IS_ARCHIVED</code>.
     */
    public void setIsArchived(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.IS_ARCHIVED</code>.
     */
    public Byte getIsArchived() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_BY</code>.
     */
    public void setRequestedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_BY</code>.
     */
    public String getRequestedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_AT</code>.
     */
    public void setRequestedAt(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.REQUESTED_AT</code>.
     */
    public Timestamp getRequestedAt() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REMARKS</code>.
     */
    public void setCtoRemarks(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REMARKS</code>.
     */
    public String getCtoRemarks() {
        return (String) get(16);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_BY</code>.
     */
    public void setCtoReviewedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_BY</code>.
     */
    public String getCtoReviewedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_AT</code>.
     */
    public void setCtoReviewedAt(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CTO_REVIEWED_AT</code>.
     */
    public Timestamp getCtoReviewedAt() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REMARKS</code>.
     */
    public void setLsdRemarks(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REMARKS</code>.
     */
    public String getLsdRemarks() {
        return (String) get(19);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_BY</code>.
     */
    public void setLsdReviewedBy(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_BY</code>.
     */
    public String getLsdReviewedBy() {
        return (String) get(20);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_AT</code>.
     */
    public void setLsdReviewedAt(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.LSD_REVIEWED_AT</code>.
     */
    public Timestamp getLsdReviewedAt() {
        return (Timestamp) get(21);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(22);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(23);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_REQUEST.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCompanyRequestRecord
     */
    public CtmsCompanyRequestRecord() {
        super(CtmsCompanyRequest.CTMS_COMPANY_REQUEST);
    }

    /**
     * Create a detached, initialised CtmsCompanyRequestRecord
     */
    public CtmsCompanyRequestRecord(BigInteger id, String rptUserGrpLv1, String rptUserGrpLv2, String rptUserGrpLv3, String ctoEndorserGrp, String englishName, String chineseName, BigInteger companyGrpId, String brNumber, String address, String phoneNumber, String remarks, String status, Byte isArchived, String requestedBy, Timestamp requestedAt, String ctoRemarks, String ctoReviewedBy, Timestamp ctoReviewedAt, String lsdRemarks, String lsdReviewedBy, Timestamp lsdReviewedAt, Timestamp createdAt, String updatedBy, Timestamp updatedAt) {
        super(CtmsCompanyRequest.CTMS_COMPANY_REQUEST);

        set(0, id);
        set(1, rptUserGrpLv1);
        set(2, rptUserGrpLv2);
        set(3, rptUserGrpLv3);
        set(4, ctoEndorserGrp);
        set(5, englishName);
        set(6, chineseName);
        set(7, companyGrpId);
        set(8, brNumber);
        set(9, address);
        set(10, phoneNumber);
        set(11, remarks);
        set(12, status);
        set(13, isArchived);
        set(14, requestedBy);
        set(15, requestedAt);
        set(16, ctoRemarks);
        set(17, ctoReviewedBy);
        set(18, ctoReviewedAt);
        set(19, lsdRemarks);
        set(20, lsdReviewedBy);
        set(21, lsdReviewedAt);
        set(22, createdAt);
        set(23, updatedBy);
        set(24, updatedAt);
    }
}
