/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormAgmtFiles;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormAgmtFilesRecord extends UpdatableRecordImpl<CtmsCtFormAgmtFilesRecord> implements Record4<BigInteger, BigInteger, String, byte[]> {

    private static final long serialVersionUID = 1719166298;

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.CT_FORM_ID</code>.
     */
    public void setCtFormId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.CT_FORM_ID</code>.
     */
    public BigInteger getCtFormId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.CONTENT</code>.
     */
    public void setContent(byte... value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_AGMT_FILES.CONTENT</code>.
     */
    public byte[] getContent() {
        return (byte[]) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<BigInteger, BigInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<BigInteger, BigInteger, String, byte[]> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<BigInteger, BigInteger, String, byte[]> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.CT_FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field4() {
        return CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value4() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormAgmtFilesRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormAgmtFilesRecord value2(BigInteger value) {
        setCtFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormAgmtFilesRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormAgmtFilesRecord value4(byte... value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormAgmtFilesRecord values(BigInteger value1, BigInteger value2, String value3, byte[] value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCtFormAgmtFilesRecord
     */
    public CtmsCtFormAgmtFilesRecord() {
        super(CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES);
    }

    /**
     * Create a detached, initialised CtmsCtFormAgmtFilesRecord
     */
    public CtmsCtFormAgmtFilesRecord(BigInteger id, BigInteger ctFormId, String name, byte[] content) {
        super(CtmsCtFormAgmtFiles.CTMS_CT_FORM_AGMT_FILES);

        set(0, id);
        set(1, ctFormId);
        set(2, name);
        set(3, content);
    }
}
