/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompany;

import java.math.BigInteger;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyRecord extends UpdatableRecordImpl<CtmsCompanyRecord> {

    private static final long serialVersionUID = 1563563690;

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CODE</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CODE</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.ENGLISH_NAME</code>.
     */
    public void setEnglishName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.ENGLISH_NAME</code>.
     */
    public String getEnglishName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CHINESE_NAME</code>.
     */
    public void setChineseName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CHINESE_NAME</code>.
     */
    public String getChineseName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.COMPANY_CAT_ID</code>.
     */
    public void setCompanyCatId(BigInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.COMPANY_CAT_ID</code>.
     */
    public BigInteger getCompanyCatId() {
        return (BigInteger) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.BR_NUMBER</code>.
     */
    public void setBrNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.BR_NUMBER</code>.
     */
    public String getBrNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.PHONE_NUMBER</code>.
     */
    public void setPhoneNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.PHONE_NUMBER</code>.
     */
    public String getPhoneNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.STATUS</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.COMPANY_GRP_ID</code>.
     */
    public void setCompanyGrpId(BigInteger value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.COMPANY_GRP_ID</code>.
     */
    public BigInteger getCompanyGrpId() {
        return (BigInteger) get(9);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.REQUESTED_BY</code>.
     */
    public void setRequestedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.REQUESTED_BY</code>.
     */
    public String getRequestedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.REQUESTED_AT</code>.
     */
    public void setRequestedAt(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.REQUESTED_AT</code>.
     */
    public Timestamp getRequestedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CTO_REMARKS</code>.
     */
    public void setCtoRemarks(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CTO_REMARKS</code>.
     */
    public String getCtoRemarks() {
        return (String) get(13);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CTO_REVIEWED_BY</code>.
     */
    public void setCtoReviewedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CTO_REVIEWED_BY</code>.
     */
    public String getCtoReviewedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CTO_REVIEWED_AT</code>.
     */
    public void setCtoReviewedAt(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CTO_REVIEWED_AT</code>.
     */
    public Timestamp getCtoReviewedAt() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.LSD_REMARKS</code>.
     */
    public void setLsdRemarks(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.LSD_REMARKS</code>.
     */
    public String getLsdRemarks() {
        return (String) get(16);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.LSD_REVIEWED_BY</code>.
     */
    public void setLsdReviewedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.LSD_REVIEWED_BY</code>.
     */
    public String getLsdReviewedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.LSD_REVIEWED_AT</code>.
     */
    public void setLsdReviewedAt(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.LSD_REVIEWED_AT</code>.
     */
    public Timestamp getLsdReviewedAt() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(19);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(20);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(21);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(22, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCompanyRecord
     */
    public CtmsCompanyRecord() {
        super(CtmsCompany.CTMS_COMPANY);
    }

    /**
     * Create a detached, initialised CtmsCompanyRecord
     */
    public CtmsCompanyRecord(BigInteger id, String code, String englishName, String chineseName, BigInteger companyCatId, String brNumber, String address, String phoneNumber, String status, BigInteger companyGrpId, String requestedBy, Timestamp requestedAt, String remarks, String ctoRemarks, String ctoReviewedBy, Timestamp ctoReviewedAt, String lsdRemarks, String lsdReviewedBy, Timestamp lsdReviewedAt, String updatedBy, Timestamp updatedAt, String createdBy, Timestamp createdAt) {
        super(CtmsCompany.CTMS_COMPANY);

        set(0, id);
        set(1, code);
        set(2, englishName);
        set(3, chineseName);
        set(4, companyCatId);
        set(5, brNumber);
        set(6, address);
        set(7, phoneNumber);
        set(8, status);
        set(9, companyGrpId);
        set(10, requestedBy);
        set(11, requestedAt);
        set(12, remarks);
        set(13, ctoRemarks);
        set(14, ctoReviewedBy);
        set(15, ctoReviewedAt);
        set(16, lsdRemarks);
        set(17, lsdReviewedBy);
        set(18, lsdReviewedAt);
        set(19, updatedBy);
        set(20, updatedAt);
        set(21, createdBy);
        set(22, createdAt);
    }
}
