/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCompanyHolder;

import java.math.BigInteger;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCompanyHolderRecord extends UpdatableRecordImpl<CtmsCompanyHolderRecord> implements Record5<BigInteger, BigInteger, BigInteger, Date, Date> {

    private static final long serialVersionUID = 722621717;

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_HOLDER.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_HOLDER.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_ID</code>.
     */
    public void setCompanyId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_ID</code>.
     */
    public BigInteger getCompanyId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_GRP_ID</code>.
     */
    public void setCompanyGrpId(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_HOLDER.COMPANY_GRP_ID</code>.
     */
    public BigInteger getCompanyGrpId() {
        return (BigInteger) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_HOLDER.START_DATE</code>.
     */
    public void setStartDate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_HOLDER.START_DATE</code>.
     */
    public Date getStartDate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_COMPANY_HOLDER.END_DATE</code>.
     */
    public void setEndDate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_COMPANY_HOLDER.END_DATE</code>.
     */
    public Date getEndDate() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigInteger, BigInteger, BigInteger, Date, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<BigInteger, BigInteger, BigInteger, Date, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsCompanyHolder.CTMS_COMPANY_HOLDER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return CtmsCompanyHolder.CTMS_COMPANY_HOLDER.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field3() {
        return CtmsCompanyHolder.CTMS_COMPANY_HOLDER.COMPANY_GRP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return CtmsCompanyHolder.CTMS_COMPANY_HOLDER.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return CtmsCompanyHolder.CTMS_COMPANY_HOLDER.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component3() {
        return getCompanyGrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component4() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value3() {
        return getCompanyGrpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord value2(BigInteger value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord value3(BigInteger value) {
        setCompanyGrpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord value4(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord value5(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCompanyHolderRecord values(BigInteger value1, BigInteger value2, BigInteger value3, Date value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCompanyHolderRecord
     */
    public CtmsCompanyHolderRecord() {
        super(CtmsCompanyHolder.CTMS_COMPANY_HOLDER);
    }

    /**
     * Create a detached, initialised CtmsCompanyHolderRecord
     */
    public CtmsCompanyHolderRecord(BigInteger id, BigInteger companyId, BigInteger companyGrpId, Date startDate, Date endDate) {
        super(CtmsCompanyHolder.CTMS_COMPANY_HOLDER);

        set(0, id);
        set(1, companyId);
        set(2, companyGrpId);
        set(3, startDate);
        set(4, endDate);
    }
}
