/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtFormPty;

import java.math.BigInteger;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormPtyRecord extends UpdatableRecordImpl<CtmsCtFormPtyRecord> implements Record7<BigInteger, BigInteger, BigInteger, String, String, String, String> {

    private static final long serialVersionUID = -1784406210;

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.CT_FORM_ID</code>.
     */
    public void setCtFormId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.CT_FORM_ID</code>.
     */
    public BigInteger getCtFormId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_ID</code>.
     */
    public void setCompanyId(BigInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_ID</code>.
     */
    public BigInteger getCompanyId() {
        return (BigInteger) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_CODE</code>.
     */
    public void setCompanyCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_CODE</code>.
     */
    public String getCompanyCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_GRP_CODE</code>.
     */
    public void setCompanyGrpCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.COMPANY_GRP_CODE</code>.
     */
    public String getCompanyGrpCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.ENGLISH_NAME</code>.
     */
    public void setEnglishName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.ENGLISH_NAME</code>.
     */
    public String getEnglishName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM_PTY.CHINESE_NAME</code>.
     */
    public void setChineseName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM_PTY.CHINESE_NAME</code>.
     */
    public String getChineseName() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, BigInteger, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigInteger, BigInteger, BigInteger, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field1() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field2() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.CT_FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigInteger> field3() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.COMPANY_GRP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.ENGLISH_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CtmsCtFormPty.CTMS_CT_FORM_PTY.CHINESE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger component3() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCompanyGrpCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getEnglishName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getChineseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value2() {
        return getCtFormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigInteger value3() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCompanyCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCompanyGrpCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEnglishName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getChineseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value1(BigInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value2(BigInteger value) {
        setCtFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value3(BigInteger value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value4(String value) {
        setCompanyCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value5(String value) {
        setCompanyGrpCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value6(String value) {
        setEnglishName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord value7(String value) {
        setChineseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CtmsCtFormPtyRecord values(BigInteger value1, BigInteger value2, BigInteger value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCtFormPtyRecord
     */
    public CtmsCtFormPtyRecord() {
        super(CtmsCtFormPty.CTMS_CT_FORM_PTY);
    }

    /**
     * Create a detached, initialised CtmsCtFormPtyRecord
     */
    public CtmsCtFormPtyRecord(BigInteger id, BigInteger ctFormId, BigInteger companyId, String companyCode, String companyGrpCode, String englishName, String chineseName) {
        super(CtmsCtFormPty.CTMS_CT_FORM_PTY);

        set(0, id);
        set(1, ctFormId);
        set(2, companyId);
        set(3, companyCode);
        set(4, companyGrpCode);
        set(5, englishName);
        set(6, chineseName);
    }
}
