/*
 * This file is generated by jOOQ.
*/
package com.test.springboot.jooq.data.jooq.tables.records;


import com.test.springboot.jooq.data.jooq.tables.CtmsCtForm;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtmsCtFormRecord extends UpdatableRecordImpl<CtmsCtFormRecord> {

    private static final long serialVersionUID = 22203070;

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.ID</code>.
     */
    public void setId(BigInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.ID</code>.
     */
    public BigInteger getId() {
        return (BigInteger) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.COPIED_FROM_ID</code>.
     */
    public void setCopiedFromId(BigInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.COPIED_FROM_ID</code>.
     */
    public BigInteger getCopiedFromId() {
        return (BigInteger) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV1</code>.
     */
    public void setRptUserGrpLv1(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV1</code>.
     */
    public String getRptUserGrpLv1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV2</code>.
     */
    public void setRptUserGrpLv2(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV2</code>.
     */
    public String getRptUserGrpLv2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV3</code>.
     */
    public void setRptUserGrpLv3(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.RPT_USER_GRP_LV3</code>.
     */
    public String getRptUserGrpLv3() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.CTO_ENDORSER_GRP</code>.
     */
    public void setCtoEndorserGrp(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.CTO_ENDORSER_GRP</code>.
     */
    public String getCtoEndorserGrp() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.TRANSACTION_TYPE</code>.
     */
    public void setTransactionType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.TRANSACTION_TYPE</code>.
     */
    public String getTransactionType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.HAS_AGMT</code>.
     */
    public void setHasAgmt(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.HAS_AGMT</code>.
     */
    public Byte getHasAgmt() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_NAME</code>.
     */
    public void setAgmtName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_NAME</code>.
     */
    public String getAgmtName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_SIGN_DATE</code>.
     */
    public void setAgmtSignDate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_SIGN_DATE</code>.
     */
    public Date getAgmtSignDate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_DURATION_TYPE</code>.
     */
    public void setAgmtDurationType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_DURATION_TYPE</code>.
     */
    public String getAgmtDurationType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_START_DATE</code>.
     */
    public void setAgmtStartDate(Date value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_START_DATE</code>.
     */
    public Date getAgmtStartDate() {
        return (Date) get(11);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_END_DATE</code>.
     */
    public void setAgmtEndDate(Date value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_END_DATE</code>.
     */
    public Date getAgmtEndDate() {
        return (Date) get(12);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW_UNIT</code>.
     */
    public void setAgmtAutoRenewUnit(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW_UNIT</code>.
     */
    public String getAgmtAutoRenewUnit() {
        return (String) get(13);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW</code>.
     */
    public void setAgmtAutoRenew(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.AGMT_AUTO_RENEW</code>.
     */
    public BigDecimal getAgmtAutoRenew() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.PRICING_TERM</code>.
     */
    public void setPricingTerm(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.PRICING_TERM</code>.
     */
    public String getPricingTerm() {
        return (String) get(15);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.PRICING_BASIS</code>.
     */
    public void setPricingBasis(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.PRICING_BASIS</code>.
     */
    public String getPricingBasis() {
        return (String) get(16);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_PAYMENT</code>.
     */
    public void setProjectedAnnualPayment(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_PAYMENT</code>.
     */
    public BigDecimal getProjectedAnnualPayment() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_RECEIVE</code>.
     */
    public void setProjectedAnnualReceive(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.PROJECTED_ANNUAL_RECEIVE</code>.
     */
    public BigDecimal getProjectedAnnualReceive() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AP</code>.
     */
    public void setIsUnknownSmallAp(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AP</code>.
     */
    public Byte getIsUnknownSmallAp() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AR</code>.
     */
    public void setIsUnknownSmallAr(Byte value) {
        set(20, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.IS_UNKNOWN_SMALL_AR</code>.
     */
    public Byte getIsUnknownSmallAr() {
        return (Byte) get(20);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.STATUS</code>.
     */
    public void setStatus(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(21);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.IS_ARCHIVED</code>.
     */
    public void setIsArchived(Byte value) {
        set(22, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.IS_ARCHIVED</code>.
     */
    public Byte getIsArchived() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.REPORTED_BY</code>.
     */
    public void setReportedBy(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.REPORTED_BY</code>.
     */
    public String getReportedBy() {
        return (String) get(23);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.REPORTED_AT</code>.
     */
    public void setReportedAt(Timestamp value) {
        set(24, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.REPORTED_AT</code>.
     */
    public Timestamp getReportedAt() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.REMARKS</code>.
     */
    public void setRemarks(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.REMARKS</code>.
     */
    public String getRemarks() {
        return (String) get(25);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.CTO_REMARKS</code>.
     */
    public void setCtoRemarks(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.CTO_REMARKS</code>.
     */
    public String getCtoRemarks() {
        return (String) get(26);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_BY</code>.
     */
    public void setCtoReviewedBy(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_BY</code>.
     */
    public String getCtoReviewedBy() {
        return (String) get(27);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_AT</code>.
     */
    public void setCtoReviewedAt(Timestamp value) {
        set(28, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.CTO_REVIEWED_AT</code>.
     */
    public Timestamp getCtoReviewedAt() {
        return (Timestamp) get(28);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.LSD_REMARKS</code>.
     */
    public void setLsdRemarks(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.LSD_REMARKS</code>.
     */
    public String getLsdRemarks() {
        return (String) get(29);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_BY</code>.
     */
    public void setLsdReviewedBy(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_BY</code>.
     */
    public String getLsdReviewedBy() {
        return (String) get(30);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_AT</code>.
     */
    public void setLsdReviewedAt(Timestamp value) {
        set(31, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.LSD_REVIEWED_AT</code>.
     */
    public Timestamp getLsdReviewedAt() {
        return (Timestamp) get(31);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.CREATED_AT</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(32, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.CREATED_AT</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(32);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(33);
    }

    /**
     * Setter for <code>PUBLIC.CTMS_CT_FORM.UPDATED_AT</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(34, value);
    }

    /**
     * Getter for <code>PUBLIC.CTMS_CT_FORM.UPDATED_AT</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(34);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<BigInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtmsCtFormRecord
     */
    public CtmsCtFormRecord() {
        super(CtmsCtForm.CTMS_CT_FORM);
    }

    /**
     * Create a detached, initialised CtmsCtFormRecord
     */
    public CtmsCtFormRecord(BigInteger id, BigInteger copiedFromId, String rptUserGrpLv1, String rptUserGrpLv2, String rptUserGrpLv3, String ctoEndorserGrp, String transactionType, Byte hasAgmt, String agmtName, Date agmtSignDate, String agmtDurationType, Date agmtStartDate, Date agmtEndDate, String agmtAutoRenewUnit, BigDecimal agmtAutoRenew, String pricingTerm, String pricingBasis, BigDecimal projectedAnnualPayment, BigDecimal projectedAnnualReceive, Byte isUnknownSmallAp, Byte isUnknownSmallAr, String status, Byte isArchived, String reportedBy, Timestamp reportedAt, String remarks, String ctoRemarks, String ctoReviewedBy, Timestamp ctoReviewedAt, String lsdRemarks, String lsdReviewedBy, Timestamp lsdReviewedAt, Timestamp createdAt, String updatedBy, Timestamp updatedAt) {
        super(CtmsCtForm.CTMS_CT_FORM);

        set(0, id);
        set(1, copiedFromId);
        set(2, rptUserGrpLv1);
        set(3, rptUserGrpLv2);
        set(4, rptUserGrpLv3);
        set(5, ctoEndorserGrp);
        set(6, transactionType);
        set(7, hasAgmt);
        set(8, agmtName);
        set(9, agmtSignDate);
        set(10, agmtDurationType);
        set(11, agmtStartDate);
        set(12, agmtEndDate);
        set(13, agmtAutoRenewUnit);
        set(14, agmtAutoRenew);
        set(15, pricingTerm);
        set(16, pricingBasis);
        set(17, projectedAnnualPayment);
        set(18, projectedAnnualReceive);
        set(19, isUnknownSmallAp);
        set(20, isUnknownSmallAr);
        set(21, status);
        set(22, isArchived);
        set(23, reportedBy);
        set(24, reportedAt);
        set(25, remarks);
        set(26, ctoRemarks);
        set(27, ctoReviewedBy);
        set(28, ctoReviewedAt);
        set(29, lsdRemarks);
        set(30, lsdReviewedBy);
        set(31, lsdReviewedAt);
        set(32, createdAt);
        set(33, updatedBy);
        set(34, updatedAt);
    }
}
